---
title: "3_scvi"
author: "zm"
date: "2024-08-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
set.seed(42)
```

```{r here}
library(here)
```

```{r libraries}
library(SingleCellExperiment)
library(tidyverse)

conflicted::conflict_prefer_all(winner = "dplyr", quiet = TRUE)
```

```{r params}
source(file = here("eval", "scripts", "r", "params.r"))
plots <- list()
```

```{r import}
sce_list <- read_rds(
  file = here("data/intermed/snrnaseq/2_sce_line_list.rds")
)
```

```{r all}
sce_all <- map(
  .x = sce_list,
  .f = function(sce) {
    # no bueno
    reducedDim(sce, "PCA") <- NULL
    reducedDim(sce, "UMAP") <- NULL

    sce
  }
) |>
  purrr::reduce(.f = cbind)

# remove all zeroes
`%notin%` <- Negate(f = `%in%`)
all_zero <- rownames(sce_all)[rowSums(counts(sce_all)) == 0]
sce_all <- sce_all[rownames(sce_all) %notin% all_zero, ]

# write
# EnvironmentModules::module_load("miniconda3")
# EnvironmentModules::module_load("openssl/3.2.1")

{
  library(zellkonverter)

  zellkonverter::writeH5AD(
    sce = sce_all,
    file = here("data/intermed/snrnaseq/3_sce_all_pre_scvi.h5ad"),
    verbose = TRUE
  )
}
```

```{r run}
{
  # library(zellkonverter)
  BiocManager::install("zellkonverter", force = TRUE, ask = FALSE)
  sce_scvi <- zellkonverter::readH5AD(
    here("data/intermed/snrnaseq/6_overall_scvi.h5ad"),
    verbose = TRUE
  )
}

scater::plotReducedDim(
  object = sce_scvi,
  dimred = "X_scVI_MDE",
  colour_by = "leiden",
  text_by = "leiden"
)

scater::plotReducedDim(
  object = sce_scvi,
  dimred = "X_scVI_MDE",
  colour_by = "PTPRC",
  swap_rownames = "gene_name"
)
```

```{r save}
write_rds(
  x = sce_scvi,
  file =  here("data/intermed/snrnaseq/7_sce_scvi.h5ad")
)
```
