---
title: "5_tumour_specific"
author: "zm"
date: "2024-09-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
set.seed(42)
```

```{r here}
library(here)
```

```{r libraries}
library(BiocParallel)
library(SingleCellExperiment)
library(tidyverse)

conflicted::conflict_prefer_all(winner = "dplyr", quiet = TRUE)
```

```{r params}
source(file = here("eval", "scripts", "r", "params.r"))
plots <- list()
```

```{r import}
sce_list <- read_rds(
  file = here("data/intermed/snrnaseq/2_sce_line_list.rds")
)
sce_all <- map(
  .x = sce_list,
  .f = function(sce) {
    # no bueno
    reducedDim(sce, "PCA") <- NULL
    reducedDim(sce, "UMAP") <- NULL

    sce
  }
) |>
  purrr::reduce(.f = cbind)

BiocManager::install("zellkonverter", force = TRUE, update = FALSE)
# sce_tumour <- zellkonverter::readH5AD(
#   here("data/intermed/snrnaseq/9_tumour_scvi.h5ad")
# )
sce_tumour <- read_rds(
  file = here("data/intermed/snrnaseq/9_tumour_scvi_sce.rds")
)
sce_tumour_counts <- sce_all[, sce_all$bc_wells %in% sce_tumour$bc_wells]
```

```{r}

```





```{r seurat}
source(here("eval/scripts/r/load_ref_list.r"))
ref_list <- load_ref_list()
colnames(ref_list$couturier) <- ref_list$couturier$Barcode
ref_list$couturier <- ref_list$couturier[, !duplicated(colnames(ref_list$couturier))]
ref_list$couturier <- ref_list$couturier[!rowSums(counts(ref_list$couturier)) == 0, ]

library(Seurat)

couturier <- as.Seurat(x = ref_list$couturier)
couturier$sample <- couturier$Sample

couturier[["rna"]] <- split(couturier[["originalexp"]], f = couturier$sample)
couturier <- NormalizeData(couturier, assay = "rna")
couturier <- FindVariableFeatures(couturier, assay = "rna")
couturier <- ScaleData(couturier, assay = "rna")
couturier <- RunPCA(couturier, assay = "rna")
couturier <- FindNeighbors(couturier, reduction = "pca")
couturier <- FindClusters(couturier, graph.name = "rna_snn")
couturier <- RunUMAP(couturier, dims = 1:30, assay = "rna")

DimPlot(
  object = couturier,
  group.by = c("sample", "cluster", "seurat_clusters")
)
DefaultAssay(couturier) <- "rna"
couturier <- IntegrateLayers(
  object = couturier,
  method = CCAIntegration,
  orig.reduction = "pca",
  new.reduction = "integrated.cca",
  verbose = TRUE
  # assay = "rna",
  # layers = "scale.data"
)

couturier <- FindNeighbors(couturier, reduction = "integrated.cca", dims = 1:30)
couturier <- FindClusters(couturier)
couturier <- RunUMAP(couturier, reduction = "integrated.cca", dims = 1:30, return.model = TRUE)

DimPlot(
  object = couturier,
  group.by = c("sample", "cluster", "seurat_clusters")
)

FeaturePlot(
  object = couturier, 
  features = "ENSG00000125398"
)

# counts(sce_tumour_counts) <- as.matrix(counts(sce_tumour_counts))
quer <- CreateSeuratObject(
  counts = counts(sce_tumour_counts) |> as.matrix(),
  meta.data = colData(sce_tumour_counts),
  assay = "rna"
)

quer <- NormalizeData(quer)
anchors <- FindTransferAnchors(
  reference = couturier,
  query = quer,
  dims = 1:30,
  reference.reduction = "pca"
)

map_quer <- MapQuery(
  anchorset = anchors,
  reference = couturier,
  query = quer,
  refdata = list(cluster = "cluster"),
  reference.reduction = "pca",
  reduction.model = "umap"
)

patchwork::wrap_plots(
  DimPlot(
    object = couturier,
    group.by = "cluster"
  ),
  DimPlot(
    map_quer,
    group.by = "predicted.cluster"
  )
)

map_quer$prev_anno <- sce_tumour_counts$individual_anno
map_quer$sample <- sce_tumour$sample
DimPlot(
  map_quer,
  group.by = c("predicted.cluster", "prev_anno", "sample")
)
patchwork::wrap_plots(
  scater::plotReducedDim(
    object = sce_tumour,
    dimred = "X_scVI_MDE",
    colour_by = I(map_quer$predicted.cluster)
  ),
  scater::plotReducedDim(
    object = sce_tumour,
    dimred = "X_scVI_MDE",
    colour_by = "individual_anno"
  )
)


DimPlot(pancreas.ref,
  reduction = "umap", group.by = "celltype", label = TRUE, label.size = 3,
  repel = TRUE
) + NoLegend() + ggtitle("Reference annotations")
p2 <- DimPlot(pancreas.query,
  reduction = "ref.umap", group.by = "predicted.celltype", label = TRUE,
  label.size = 3, repel = TRUE
)
```

```{r }
library(singleCellNet)

source(here("eval/scripts/r/load_ref_list.r"))

# zellkonverter::writeH5AD(sce = ref_list$couturier, file = here("data/intermed/snrnaseq/couturier.h5ad"))

# start with refs
# load each reference
ref_list <- load_ref_list()
colnames(ref_list$couturier) <- ref_list$couturier$Barcode

ref_list$couturier <- ref_list$couturier[, !duplicated(colnames(ref_list$couturier))]

# gene_intersect <- intersect(
#       x = rownames(sce_tumour_counts),
#       y = rownames(ref_list$couturier)
#     )

gene_intersect <- rownames(sce_tumour)

set.seed(42)
split_reference <- singleCellNet::splitCommon(
  sampTab = colData(ref_list$couturier) |> as.data.frame(),
  ncells = 100,
  dLevel = "cluster"
)

matrix_full <- logcounts(ref_list$couturier) |> as.matrix()
matrix_full <- matrix_full[!rowSums(matrix_full) == 0, ]

matrix_train <- matrix_full[
  rownames(matrix_full) %in% gene_intersect,
  colnames(matrix_full) %in% rownames(split_reference$train)
]

train_reference <- singleCellNet::scn_train(
  stTrain = split_reference$train,
  expTrain = matrix_train,
  dLevel = "cluster",
  colName_samp = "Barcode",
  nTopGenes = 500,
  nRand = 50,
  nTrees = 1000,
  nTopGenePairs = 25
)

split_reference_validate <- singleCellNet::splitCommon(
  sampTab = split_reference$val,
  ncells = 100,
  dLevel = "cluster"
)

# no defined colnames == numbers
matrix_test <-
  matrix_full[
    rownames(matrix_full) %in% gene_intersect,
    colnames(matrix_full) %in% rownames(split_reference$val)
  ]

predict_res <- singleCellNet::scn_predict(
  cnProc = train_reference$cnProc,
  expDat = matrix_test,
  nrand = 50
)

assess_res <- singleCellNet::assess_comm(
  ct_scores = predict_res,
  stTrain = split_reference$train,
  stQuery = split_reference$val,
  dLevelSID = "Barcode",
  classTrain = "cluster",
  classQuery = "cluster",
  nRand = 50
)

singleCellNet::plot_PRs(assess_res)

nrand <- 50
sla <- as.vector(split_reference$val$cluster)
names(sla) <- as.vector(split_reference$val$Barcode)
sla_rand <- rep("rand", nrand)
names(sla_rand) <- paste("rand_", 1:nrand, sep = "")
sla <- append(sla, sla_rand) # include in the random cells profile created

singleCellNet::sc_hmClass(
  classMat = predict_res,
  grps = sla,
  max = 500,
  isBig = TRUE
)
```
```
