---
title: "3_annotation_all"
author: "zm"
date: "2024-06-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
set.seed(42)
```

```{r here}
library(here)
```

```{r libraries}
library(BiocParallel)
library(SingleCellExperiment)
library(tidyverse)

conflicted::conflict_prefer_all(winner = "dplyr", quiet = TRUE)
```

```{r names}
# extract names from folders
sample_names <- list.dirs(
  path = here("data", "raw", "splitpipe", "combined"),
  recursive = FALSE
) |>
  str_subset(pattern = "GL") |>
  basename()

sample_groups <- sample_names |>
  str_extract(
    pattern = "[^_]+"
  )

sample_list <- list(
  sample_names[1:3],
  sample_names[4:6],
  sample_names[7:9],
  sample_names[10:12]
) |>
  set_names(
    sample_groups[1],
    sample_groups[4],
    sample_groups[7],
    sample_groups[10],
  )
```

```{r import}
# the important scvi parts are the dimreds
sce_list <- read_rds(
  file = here("data", "processed", "1_2_filtered", "sce_combined.rds")
)
sce_all <- purrr::reduce(sce_list, .f = cbind)
```

```{r new_dimred}
sce_list <- imap(
  .x = sce_list,
  .f = function(sce, i) {
    # calculated in jupyter notebook
    reducedDim(sce, "X_scVI") <- read_csv(
      file = here("data", "processed", "2_1_scvi", paste(i, "latent_dims.csv", sep = "_")),
      col_select = -1,
      skip = 1,
      col_names = FALSE,
      show_col_types = FALSE
    ) |>
      as.matrix()

    reducedDim(sce, "X_scVI_MDE") <- read_csv(
      file = here("data", "processed", "2_1_scvi", paste(i, "MDE.csv", sep = "_")),
      show_col_types = FALSE
    ) |>
      select(-1) |>
      as.matrix()

    sce$leiden <- read_csv(
      file = here("data", "processed", "2_1_scvi", paste(i, "leiden.csv", sep = "_")),
      show_col_types = FALSE
    ) |>
      pull(leiden) |>
      as.factor()

    sce
  }
)
```

```{r norm_list}
sce_norm_list <- imap(
  .progress = TRUE,
  .x = sce_list,
  .f = function(sce, i) {
    # read in
    norm_matrix <- vroom::vroom(
      file = here("data", "processed", "2_1_scvi", paste(i, "norm.csv", sep = "_")),
      show_col_types = FALSE
    ) |>
      column_to_rownames(var = "...1") |>
      as.matrix()

    SingleCellExperiment(
      assays = list(
        counts = norm_matrix
      ),
      reducedDims = reducedDims(sce),
      colData = colData(sce),
      rowData = rowData(sce) |>
        as_tibble() |>
        filter(gene_id %in% rownames(norm_matrix))
    )
  }
)
```

```{r sce_all}
sce_scvi <- zellkonverter::readH5AD(
  file = here("data", "processed", "2_1_scvi", "sce_all_post.h5ad")
)

norm_matrix <- vroom::vroom(
  file = here("data", "processed", "2_1_scvi", "sce_all_norm.csv"),
  show_col_types = FALSE
) |>
  column_to_rownames(var = "...1") |>
  as.matrix()


sce_scvi_norm <- SingleCellExperiment(
  assays = list(
    norm = norm_matrix
  ),
  reducedDims = reducedDims(sce_scvi),
  colData = colData(sce_scvi),
  rowData = rowData(sce_scvi) |>
    as_tibble() |>
    filter(gene_id %in% rownames(norm_matrix))
)
# bueno?
logcounts(sce_scvi_norm) <- log2(assay(sce_scvi_norm, "norm"))
```




```{r overall}
# i like this one
umap_res <- uwot::umap(
  X = reducedDim(sce_scvi, "X_scVI"),
  metric = "euclidean",
  init = "normlaplacian",
  seed = 42 * 42,
  n_threads = 40
)
reducedDim(sce_scvi, "X_scVI_UMAP") <- umap_res

scater::plotReducedDim(
  object = sce_scvi,
  dimred = "X_scVI_UMAP",
  colour_by = "leiden",
  text_by = "leiden"
)

# this is jank
clust_dbscan <- dbscan::dbscan(
  x = reducedDim(sce_scvi, "X_scVI_MDE"),
  eps = 0.325
)
sce_scvi$dbscan <- clust_dbscan$cluster |>
  as.factor()

scater::plotReducedDim(
  object = sce_scvi,
  dimred = "X_scVI_MDE",
  colour_by = "dbscan",
  text_by = "dbscan"
) +
  theme(aspect.ratio = 1) +
  scale_x_reverse() + scale_y_reverse()


plot_dimred <- c("sample", "leiden", "dbscan") |>
  set_names() |>
  map(
    .f = function(x) {
      if (x == "sample") {
        text <- NULL
      } else {
        text <- x
      }
      p <- scater::plotReducedDim(
        object = sce_scvi,
        dimred = "X_scVI_MDE",
        colour_by = x,
        text_by = text
      ) +
        ggh4x::force_panelsizes(
          rows = unit(10, "cm"),
          cols = unit(10, "cm")
        )
      p$facet$params$force.respect <- TRUE
      p
    }
  ) |>
  patchwork::wrap_plots()

ggsave(
  filename = here("output", "plots", "3_1_dimred", "overall.pdf"),
  plot = plot_dimred,
  device = cairo_pdf,
  width = 75,
  height = 75,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("output", "plots", "3_1_dimred", "overall.pdf"),
    here("output", "plots", "3_1_dimred", "overall.pdf")
  ),
  stdout = NULL
)
```

```{r markers}
clust_of_interest <- c(10, 11, 12, 16, 20, 21, 22)

change_per_clust <- read_csv(
  file = here("data", "processed", "2_1_scvi", "sce_all_cluster.csv"),
  show_col_types = FALSE
) |>
  rename(gene_id = 1)

change_per_clust <- change_per_clust |>
  left_join(
    y = rowData(sce_scvi_norm) |>
      as_tibble() |>
      select(gene_id, gene_name),
    by = join_by(gene_id)
  ) |>
  relocate(gene_name) |>
  mutate(gene_name = as.character(gene_name))

clust_markers <- clust_of_interest |>
  set_names() |>
  map(
    .f = function(x) {
      change_per_clust |>
        group_by(group1) |>
        slice_head(n = 9) |>
        ungroup() |>
        filter(group1 == x) |>
        select(gene_id, gene_name)
    }
  )

reducedDim(sce_scvi_norm, "X_scVI_UMAP") <- reducedDim(sce_scvi, "X_scVI_UMAP")

plot_clust_markers <- imap(
  .progress = TRUE,
  .x = clust_markers,
  .f = function(x, i) {
    x$gene_name |>
      set_names() |>
      map(
        .f = function(y) {
          scater::plotReducedDim(
            object = sce_scvi_norm,
            dimred = "X_scVI_MDE",
            colour_by = y,
            # by_exprs_values = "norm",
            swap_rownames = "gene_name"
          )
        }
      )
  }
)

iwalk(
  .x = plot_clust_markers,
  .f = function(x, i) {
    plot_list <- map(
      .x = x,
      .f = function(y) {
        p <- y +
          ggh4x::force_panelsizes(
            rows = unit(10, "cm"),
            cols = unit(10, "cm")
          )
        p$facet$params$force.respect <- TRUE

        p
      }
    )

    ggsave(
      filename = here("output", "plots", "3_2_cluster_markers", paste(i, ".pdf", sep = "")),
      plot = list(
        plot_dimred[[1]],
        plot_dimred[[2]]
      ) |>
        append(plot_list) |>
        patchwork::wrap_plots(),
      device = cairo_pdf,
      width = 75,
      height = 75,
      units = "cm"
    )
    system2(
      command = "pdfcrop",
      args = c(
        here("output", "plots", "3_2_cluster_markers", paste(i, ".pdf", sep = "")),
        here("output", "plots", "3_2_cluster_markers", paste(i, ".pdf", sep = ""))
      ),
      stdout = NULL
    )
  }
)
```

```{r clust_enrich}
clust_markers_enrich <- clust_of_interest |>
  set_names() |>
  map(
    .f = function(x) {
      top <- change_per_clust |>
        filter(group1 == x) |>
        filter(is_de_fdr_0.05 == TRUE) |>
        # slice_head(n = 100) |>
        pull(gene_name)

      if (is_empty(top)) {
        top <- change_per_clust |>
          filter(group1 == x) |>
          # filter(is_de_fdr_0.05 == TRUE) |>
          slice_head(n = 100) |>
          pull(gene_name)
      }

      library(enrichR)

      res <- enrichR::enrichr(
        genes = top,
        databases = c(
          # can add more if needed - but this works best
          "CellMarker_2024"
        )
      )
      res
    }
  )

plot_clust_markers_enrich <- imap(
  .x = clust_markers_enrich,
  .f = function(x, i) {
    p <- enrichR::plotEnrich(
      df = x[[1]]
    ) +
      ggtitle(label = i) +
      theme(aspect.ratio = 1) +
      ggh4x::force_panelsizes(
        rows = unit(10, "cm"),
        cols = unit(10, "cm")
      )
    p$facet$params$force.respect <- TRUE

    p
  }
)

ggsave(
  filename = here("output", "plots", "3_3_cluster_enrich", "collated.pdf"),
  plot = list(
    plot_dimred[[1]],
    plot_dimred[[2]]
  ) |>
    append(plot_clust_markers_enrich) |>
    patchwork::wrap_plots(),
  device = cairo_pdf,
  width = 100,
  height = 100,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("output", "plots", "3_3_cluster_enrich", "collated.pdf"),
    here("output", "plots", "3_3_cluster_enrich", "collated.pdf")
  ),
  stdout = NULL
)
```

```{r normal_ms}
source(file = here("eval", "scripts", "r", "normal_sets_ms.R"))

normal_sets_ms$neuron <- c(
  normal_sets_ms$neuron, "RBFOX3"
)
plot_normal_sets <- imap(
  .progress = TRUE,
  .x = normal_sets_ms,
  .f = function(x, j) {
    # start with clust and sample
    a <- list(
      scater::plotReducedDim(
        object = sce_scvi,
        dimred = "X_scVI_MDE",
        colour_by = "leiden",
        text_by = "leiden"
      ),
      scater::plotReducedDim(
        object = sce_scvi,
        dimred = "X_scVI_MDE",
        colour_by = "sample"
      )
    )
    # loop through each gene
    b <- x |>
      set_names() |>
      map(
        .f = function(y) {
          if (!y %in% rowData(sce_scvi)$gene_name) {
            p <- scater::plotReducedDim(
              object = sce_scvi,
              dimred = "X_scVI_MDE",
              # colour_by = y,
              swap_rownames = "gene_name"
            )
          } else {
            p <- scater::plotReducedDim(
              object = sce_scvi,
              dimred = "X_scVI_MDE",
              colour_by = y,
              swap_rownames = "gene_name"
            )
          }
          return(p)
        }
      )
    # combine
    append(a, b)
  }
)

EnvironmentModules::module_load("ImageMagick/7.0.9-5")

iwalk(
  .progress = TRUE,
  .x = plot_normal_sets,
  .f = function(x, i) {
    x <- map(
      .x = x,
      .f = function(y) {
        y <- y +
          ggh4x::force_panelsizes(
            rows = unit(7.5, "cm"),
            cols = unit(7.5, "cm")
          )
        y$facet$params$force.respect <- TRUE
        y
      }
    )

    ggsave(
      filename = here("output", "plots", "3_4_ms_normal", paste0(i, ".jpg")),
      plot = patchwork::wrap_plots(x, ncol = 5),
      width = 100,
      height = 100,
      units = "cm"
    )
    system2(
      command = "convert",
      args = c(
        here("output", "plots", "3_4_ms_normal", paste0(i, ".jpg")),
        "-trim",
        here("output", "plots", "3_4_ms_normal", paste0(i, ".jpg"))
      ),
      stdout = NULL
    )
  }
)
```

```{r mds}
# this doesn't affect downstream that much
subset_union <- map(
  .x = sce_norm_list[!names(sce_norm_list) == "GL0128"],
  .f = function(sce) {
    rownames(sce)
  }
) |>
  purrr::reduce(.f = intersect)

bulk_counts <- scuttle::summarizeAssayByGroup(
  x = sce_all[, !(str_detect(sce_all$sample, "GL0128"))],
  ids = colData(sce_all)$sample[!(str_detect(colData(sce_all)$sample, "GL0128"))],
  BPPARAM = MulticoreParam(
    workers = length(parallelly::availableWorkers())
  )
)

# choose aggregate metric here - this has large effects
bulk_counts_matrix <- assay(bulk_counts, "sum") |>
  as.matrix()
# norm_lib <- edgeR::normLibSizes(bulk_counts_matrix)
# bulk_counts_matrix <- bulk_counts_matrix |>
# apply(MARGIN = 2, FUN = function(x) {x * norm_lib})

# bulk_counts_matrix <- bulk_counts_matrix * norm_lib
mds <- limma::plotMDS(
  x = bulk_counts_matrix[subset_union, ], top = 500, dim.plot = c(1, 2), gene.selection = "common"
)

dat <- mds$eigen.vectors |>
  as_tibble() |>
  bind_cols(tibble(sample = colnames(bulk_counts_matrix))) |>
  mutate(
    line = str_sub(sample, end = 6),
    type = str_sub(sample, start = 8)
  ) |>
  mutate(line = as.factor(line))

mds_plot <- dat |>
  mutate(MDS_1 = V1, MDS_2 = V2, Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = MDS_1,
      y = MDS_2,
      colour = Line,
      fill = Line,
      shape = Sample
    )
  ) +
  ggforce::geom_mark_ellipse(
    mapping = aes(
      group = Line
    ),
    expand = unit(0, "mm")
  ) +
  geom_point(size = 5) +
  geom_point(key_glyph = draw_key_rect) +
  geom_point() +
  scale_colour_manual(values = line_cols) +
  scale_fill_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  xlab(paste0("MDS_1\n", round(mds$var.explained[1] * 100, 2), "% Variance Explained")) +
  ylab(paste0("MDS_1\n", round(mds$var.explained[2] * 100, 2), "% Variance Explained")) +
  guides(
    colour = guide_legend(title = "Line"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )

dist_measures <- map(
  .x = dat$line |> unique(),
  .f = function(x) {
    dat_filt <- dat |>
      filter(line == x) |>
      select(V1, V2, sample, line, type)

    tiss <- dat_filt |>
      filter(type == "T")

    map(
      .x = c("PDN", "PDO"),
      .f = function(y) {
        dat_type <- dat_filt |>
          filter(type == y)

        a <- tiss |>
          select(-c(sample, line, type))
        b <- dat_type |>
          select(-c(sample, line, type))

        c <- tibble("a" = t(a) |> as.vector(), "b" = t(b) |> as.vector()) |>
          mutate(c = (a - b)^2)

        dist <- sqrt(sum(c$c))

        # dist <- sqrt(
        #   (tiss$V1 - dat_type$V1)^2 +
        #     (tiss$V2 - dat_type$V2)^2 +
        #     (tiss$V3 - dat_type$V3)
        # )

        tibble(
          line = x,
          type = y,
          dist = dist
        )
      }
    ) |>
      bind_rows(
        tibble(
          line = x,
          type = "T",
          dist = 0
        )
      )
  }
) |>
  bind_rows()

dist_measures |>
  ggplot(
    mapping = aes(
      x = dist,
      y = line,
      colour = line,
      shape = type
    )
  ) +
  geom_point(size = 5) +
  theme(aspect.ratio = 1)
```

```{r numbat_comparison}
numbat_res <- map(
  .x = names(sce_list),
  .f = function(x) {
    library(numbat)
    nb <- Numbat$new(out_dir = here("data", "processed", "2_4_numbat_out", x))

    nb$clone_post |>
      as_tibble() |>
      rename(bc_wells_corr = cell, numbat_res = compartment_opt) |>
      select(bc_wells_corr, numbat_res, p_cnv) |>
      mutate(line = x) |>
      relocate(line)
  }
) |>
  bind_rows()

colData(sce_scvi_norm) <- colData(sce_scvi_norm) |>
  as_tibble() |>
  # select(-c(line, numbat_res, p_cnv)) |>
  mutate(bc_wells_corr = str_replace(bc_wells, pattern = "__", replacement = "_")) |>
  left_join(
    y = numbat_res |>
      select(bc_wells_corr, numbat_res, p_cnv, line)
  ) |>
  DataFrame()

sce_scvi_norm$numbat_filt <- case_when(
  sce_scvi_norm$p_cnv < 0.05 ~ "normal",
  .default = "tumour"
)
patchwork::wrap_plots(
  scater::plotReducedDim(
    object = sce_scvi_norm,
    dimred = "X_scVI_MDE",
    colour_by = "numbat_res"
  ) +
    scale_x_reverse() +
    scale_y_reverse() +
    theme(aspect.ratio = 1),
  scater::plotReducedDim(
    object = sce_scvi_norm,
    dimred = "X_scVI_MDE",
    colour_by = "numbat_filt"
  ) +
    scale_x_reverse() +
    scale_y_reverse() +
    theme(aspect.ratio = 1)
  # scater::plotReducedDim(
  #   object = sce_scvi_norm,
  #   dimred = "X_scVI_UMAP",
  #   colour_by = "numbat_res"
  # ) +
  #   scale_x_reverse() +
  #   scale_y_reverse() +
  #   theme(aspect.ratio = 1),
  # scater::plotReducedDim(
  #   object = sce_scvi_norm,
  #   dimred = "X_scVI_UMAP",
  #   colour_by = "numbat_filt"
  # ) +
  #   scale_x_reverse() +
  #   scale_y_reverse() +
  #   theme(aspect.ratio = 1)
)

patchwork::wrap_plots(
  scater::plotReducedDim(
    object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
    dimred = "X_scVI_MDE",
    colour_by = "numbat_res"
  ) +
    scale_x_reverse() +
    scale_y_reverse() +
    theme(aspect.ratio = 1),
  scater::plotReducedDim(
    object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
    dimred = "X_scVI_MDE",
    colour_by = "leiden",
    text_by = "leiden"
  ) +
    scale_x_reverse() +
    scale_y_reverse() +
    theme(aspect.ratio = 1),
  scater::plotReducedDim(
    object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
    dimred = "X_scVI_MDE",
    colour_by = "line",
    shape_by = "numbat_res"
  ) +
    scale_x_reverse() +
    scale_y_reverse(),
  scater::plotReducedDim(
    object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
    dimred = "X_scVI_MDE",
    colour_by = "p_cnv"
  ) +
    scale_x_reverse() +
    scale_y_reverse() +
    theme(aspect.ratio = 1),
  # scater::plotReducedDim(
  #   object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
  #   dimred = "X_scVI_UMAP",
  #   colour_by = "numbat_res"
  # ) +
  #   scale_x_reverse() +
  #   scale_y_reverse() +
  #   theme(aspect.ratio = 1),
  # scater::plotReducedDim(
  #   object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
  #   dimred = "X_scVI_UMAP",
  #   colour_by = "leiden",
  #   text_by = "leiden"
  # ) +
  #   scale_x_reverse() +
  #   scale_y_reverse() +
  #   theme(aspect.ratio = 1),
  # scater::plotReducedDim(
  #   object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
  #   dimred = "X_scVI_UMAP",
  #   colour_by = "line",
  #   shape_by = "numbat_res"
  # ) +
  #   scale_x_reverse() +
  #   scale_y_reverse() +
  #   theme(aspect.ratio = 1),
  # scater::plotReducedDim(
  #   object = sce_scvi_norm[, !sce_scvi_norm$line == "GL0128"],
  #   dimred = "X_scVI_UMAP",
  #   colour_by = "p_cnv"
  # ) +
  #   scale_x_reverse() +
  #   scale_y_reverse() +
  #   theme(aspect.ratio = 1),
  ncol = 4
)

sce_scvi_norm$numbat_filt <- case_when(
  sce_scvi_norm$p_cnv < 0.5 |
    sce_scvi_norm$leiden %in% c(16, 21, 22) ~ "normal",
  .default = "tumour"
)
scater::plotReducedDim(
  object = sce_scvi_norm,
  # object = sce_scvi_norm,
  dimred = "X_scVI_MDE",
  colour_by = "numbat_filt",
  # swap_rownames = "gene_name"
) +
  theme(aspect.ratio = 1)


norm_cells <- colData(sce_scvi_norm) |>
  as_tibble() |>
  mutate(
    line = str_sub(sample, end = 6),
    type = str_sub(sample, start = 8)
  ) |>
  select(bc_wells, sample, line, type, numbat_filt)

reducedDim(sce_all, "X_scVI_MDE") <- reducedDim(sce_scvi, "X_scVI_MDE")
sce_tumour <- sce_all[, norm_cells |> filter(numbat_filt == "tumour") |> pull(bc_wells)]
sce_tumour$type <- str_sub(sce_tumour$sample, start = 8)
sce_tumour$line <- str_sub(sce_tumour$sample, end = 6)

odd <- read_csv(
  file = here("data", "processed", "3_1_norm_labels", "odd_cells.csv"),
  show_col_types = FALSE
)

# scater::plotReducedDim(
#   object = sce_tumour,
#   dimred = "X_scVI_MDE",
#   colour_by = I(sce_all$bc_wells %in% odd$bc_wells)
# )
# may as well
final <- reducedDim(sce_tumour, "X_scVI_MDE") |>
  as_tibble(rownames = "bc_wells") |>
  filter(V1 < -2.5) |>
  pull(bc_wells)

sce_tumour <- sce_tumour[, !sce_tumour$bc_wells %in% final]

# zellkonverter::writeH5AD(
#   sce = sce_tumour,
#   file = here("data", "processed", "2_5_tumour_only", "sce_tumour.h5ad")
# )

# use full genes for individual work
sce_combined <- readRDS(
  "/vast/scratch/users/moore.z/pdo_pdn_comparison/data/processed/1_2_filtered/sce_combined.rds"
)
# sce_tumour <- zellkonverter::readH5AD(
#    here("data", "processed", "2_5_tumour_only", "sce_tumour.h5ad")
# )
# iwalk(
#   .x = sce_combined,
#   .f = function(sce, i) {
#     library(zellkonverter)
#     sce_filt <- sce[, sce$bc_wells %in% colnames(sce_tumour)]
#     writeH5AD(
#       sce = sce_filt,
#       file = here("data", "processed", "2_5_tumour_only", paste0(i, "_tumour.h5ad"))
#     )
#   }
# )
```

```{r odd}
# these clustered exceptionally far apart from the rest of the tumour cells
# scater::plotReducedDim(
#   object = sce_scvi_norm,
#   dimred = "X_scVI_MDE",
#   colour_by = I(sce_scvi_norm$bc_wells %in% odd_cells$bc_wells)
# ) +
#   theme(aspect.ratio = 1)
```

```{r colours}
line_cols <- c("#173f5f", "#3caea3", "#f6d55c", "#ed553b")
# seed_cols <- c("#e47093", "#61c07f", "#a28ae1", "#c1a148")
sample_cols <- map(
  .x = line_cols,
  .f = function(x) {
    tinter::tinter(
      x = x,
      steps = 2
    )
  }
) |>
  unlist() |>
  set_names(nm = sample_names)
type_shapes <- c(16, 17, 15, 15) |> set_names(c("PDN", "PDO", "T", "TIS"))
sce_scvi_norm$type <- str_sub(sce_scvi_norm$sample, start = 8)

plot_data <- reducedDim(
  x = sce_scvi,
  type = "X_scVI_MDE"
) |>
  as_tibble(
    rownames = "bc_wells",
    .name_repair = "unique"
  ) |>
  rename(MDE_1 = 2, MDE_2 = 3) |>
  left_join(
    y = colData(sce_scvi) |>
      as_tibble()
    # by = join_by(bc_wells)
  ) |>
  left_join(
    y = norm_cells,
    # by = join_by(bc_wells)
  ) |>
  mutate(
    high_immune = case_when(
      MDE_1 < -1.5 & MDE_2 > 2 ~ "immune"
    ),
    high_oligo = case_when(
      MDE_1 < -2 & MDE_2 < 1 ~ "oligo"
    )
  ) |>
  left_join(
    y = logcounts(sce_scvi)[rowData(sce_scvi)$gene_name == "PTPRC", ] %>%
      as_tibble(rownames = "bc_wells") |>
      rename(PTPRC = value),
    # by = join_by(bc_wells)
  ) |>
  left_join(
    y = logcounts(sce_scvi)[rowData(sce_scvi)$gene_name == "MBP", ] %>%
      as_tibble(rownames = "bc_wells") |>
      rename(MBP = value),
    # by = join_by(bc_wells)
  )

all_umap <- plot_data |>
  slice(sample(1:n())) |>
   filter(!line == "GL0128") |> 
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = Line,
      fill = Line,
      shape = Sample
    )
  ) +
  geom_point(
    size = 2,
    key_glyph = "rect"
  ) +
  geom_point() +
  scale_colour_manual(values = line_cols) +
  scale_fill_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_legend(title = "Line"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )
  # ggh4x::force_panelsizes(
  #   rows = unit(10, "cm"),
  #   cols = unit(10, "cm")
  # ) +
  # ggtitle("All Samples Integrated")

type_umap <- plot_data |>
  slice(sample(1:n())) |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = Sample,
      # fill = Sample,
      shape = Sample
    )
  ) +
  geom_point(
    size = 2,
    key_glyph = "rect"
  ) +
  geom_point() +
  # scale_colour_manual(values = line_cols) +
  # scale_fill_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_legend(title = "Sample"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  ) +
  ggh4x::force_panelsizes(
    rows = unit(10, "cm"),
    cols = unit(10, "cm")
  ) +
  ggtitle("All Samples Integrated")

numbat_umap <- plot_data |>
  slice(sample(1:n())) |>
  filter(!line == "GL0128") |> 
  mutate(Sample = type, Line = line, Class = str_to_title(numbat_filt)) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = Class,
      fill = Class,
      shape = Sample
    )
  ) +
  geom_point(
    size = 2,
    key_glyph = "rect"
  ) +
  geom_point() +
  scale_colour_manual(values = c("#77c298", "#e84d60")) +
  scale_fill_manual(values = c("#77c298", "#e84d60")) +
  scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_legend(title = "Class"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )
  # ggh4x::force_panelsizes(
  #   rows = unit(10, "cm"),
  #   cols = unit(10, "cm")
  # ) +
  # ggtitle("All Samples Integrated")

ptprc_umap <- plot_data |>
  slice(sample(1:n())) |>
  filter(!line == "GL0128") |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  mutate(
    Ellipse = case_when(
      high_immune == "immune" ~ "Immune",
      # high_oligo == "oligo" ~ "Oligo"
    )
  ) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = PTPRC,
      # fill = Line,
      # shape = Sample,
      group = Ellipse
    )
  ) +
  geom_point(
    size = 2,
    key_glyph = "rect"
  ) +
  scale_colour_viridis_c() +
  ggforce::geom_mark_ellipse(
    inherit.aes = FALSE,
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      group = Ellipse,
      # colour = Ellipse,
      filter = !is.na(Ellipse)
    ),
    colour = "black",
    expand = unit(2, "mm")
  ) +
  geom_point() +
  # scale_colour_manual(values = c("#056517", "#de1a24")) +
  # scale_fill_manual(values = c("#056517", "#de1a24")) +
  # scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_colourbar(title = expression(italic("PTPRC"))),
    # shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )
mbp_umap <- plot_data |>
  slice(sample(1:n())) |>
  filter(!line == "GL0128") |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  mutate(
    Ellipse = case_when(
      # high_immune == "immune" ~ "Immune",
      high_oligo == "oligo" ~ "Oligo"
    )
  ) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = MBP,
      # fill = Line,
      # shape = Sample,
      group = Ellipse
    )
  ) +
  geom_point(
    size = 2,
    key_glyph = "rect"
  ) +
  scale_colour_viridis_c() +
  ggforce::geom_mark_ellipse(
    inherit.aes = FALSE,
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      group = Ellipse,
      # colour = Ellipse,
      filter = !is.na(Ellipse)
    ),
    colour = "black",
    expand = unit(2, "mm")
  ) +
  geom_point() +
  # scale_colour_manual(values = c("#056517", "#de1a24")) +
  # scale_fill_manual(values = c("#056517", "#de1a24")) +
  # scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_colourbar(title = expression(italic("MBP"))),
    # shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )

ggplot2Colours <- function(n) {
  if (n %% 1 == 0 && n > 0) {
    hcl(h = seq(15, 375, length = n + 1), c = 100, l = 65)[1:n]
  } else {
    print("pos. int. req.")
  }
}
# pie_cols <- ggplot2Colours(n = 3) |>
#   set_names("PDN", "PDO", "TIS")

oligo_pie <- plot_data |>
  filter(!line == "GL0128") |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  mutate(
    Ellipse = case_when(
      # high_immune == "immune" ~ "Immune",
      high_oligo == "oligo" ~ "Oligo"
    )
  ) |>
  filter(!is.na(Ellipse)) |>
  group_by(Sample, Ellipse) |>
  count() |>
  group_by(Ellipse) |>
  mutate(Percent = n / sum(n) * 100) |>
  mutate(labels = paste(round(Percent, digits = 2), "%")) |>
  ggplot(
    mapping = aes(
      x = "",
      y = Percent,
      fill = Sample
    )
  ) +
  scale_fill_manual(values = pie_cols) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  geom_text(
    aes(label = labels),
    position = position_stack(vjust = 0.5),
    show.legend = FALSE
  ) +
  # facet_wrap(~ellipse) +
  theme(
    aspect.ratio = 1,
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background = element_rect(fill = "white", colour = NA)
  )
immune_pie <- plot_data |>
  filter(!line == "GL0128") |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  mutate(
    Ellipse = case_when(
      high_immune == "immune" ~ "Immune",
      # high_oligo == "oligo" ~ "Oligo"
    )
  ) |>
  filter(!is.na(Ellipse)) |>
  group_by(Sample, Ellipse) |>
  count() |>
  group_by(Ellipse) |>
  mutate(Percent = n / sum(n) * 100) |>
  mutate(labels = paste(round(Percent, digits = 2), "%")) |>
  ggplot(
    mapping = aes(
      x = "",
      y = Percent,
      fill = Sample
    )
  ) +
  scale_fill_manual(values = pie_cols) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  geom_text(
    aes(label = labels),
    position = position_stack(vjust = 0.5),
    show.legend = FALSE
  ) +
  # facet_wrap(~ellipse) +
  theme(
    aspect.ratio = 1,
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.background = element_rect(fill = "white", colour = NA)
  )

dist_plot <- dist_measures |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = dist,
      y = Line,
      colour = Line,
      fill = Line,
      shape = Sample
    )
  ) +
  geom_point(
    size = 5,
    key_glyph = "rect"
  ) +
  geom_point() +
  scale_y_discrete(limits = rev) +
  scale_colour_manual(values = line_cols) +
  scale_fill_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  labs(x = "Distance from Tissue (A.U)") +
  guides(
    colour = guide_legend(title = "Line"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.title.y = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )
# ggh4x::force_panelsizes(
#   rows = unit(7.5, "cm"),
#   cols = unit(10, "cm")
# )

scater::plotReducedDim(
  object = sce_scvi_norm,
  dimred = "X_scVI_MDE",
  colour_by = "line",
  shape_by = "type"
) +
  scale_colour_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  theme(aspect.ratio = 1)
```

```{r snp}
sample_uids <- list(
  GL0028 = list(
    "TIS" = "207686170123_R01C02",
    "PDO" = "207686170123_R12C01",
    "PDN" = "208115890066_R10C02"
  ),
  GL0038 = list(
    "TIS" = "207686170123_R02C01",
    "PDO" = "207686170123_R11C01",
    "PDN" = "208146560163_R11C02"
  ),
  GL0095 = list(
    "TIS" = "208115890028_R02C01",
    "PDO" = "208115890066_R04C01",
    "PDN" = "208115890028_R11C01"
  ),
  GL0128 = list(
    "TIS" = "208115890028_R04C02",
    "PDO" = "208115890066_R06C01",
    "PDN" = "208115890066_R12C02"
  )
)
source("/stornext/Bioinf/data/lab_brain_cancer/data_processed/SNP/snp_process/scripts/list_dir_n_depth.R")
segment_paths <- list_dir_n_depth(
  path_use = "/stornext/Bioinf/data/lab_brain_cancer/data_processed/SNP/plots/",
  depth_keep = 2
) |>
  list.files(
    pattern = "segments",
    full.names = TRUE
  )

segment_paths_filt <-
  str_detect(
    segment_paths,
    pattern = unlist(sample_uids) |>
      paste(collapse = "|")
  ) %>%
  segment_paths[.]

segment_files <- map(
  .x = segment_paths_filt,
  .f = read_csv,
  show_col_type = FALSE
)

names(segment_files) <- imap(
  .x = sample_uids,
  .f = function(x, i) {
    paste(i, names(x), sep = "_")
  }
) |>
  unlist(use.names = FALSE)

segment_files <- imap(
  .x = segment_files,
  .f = function(x, i) {
    x |>
      mutate(sample = i) |>
      mutate(
        line = str_split(sample, pattern = "_") |> map(1) |> unlist(),
        type = str_split(sample, pattern = "_") |> map(2) |> unlist()
      )
  }
)

dat <- bind_rows(
  segment_files
)

dat <- dat |>
  group_by(sample, chr) |>
  mutate(diff = lead(startpos) - endpos) |>
  ungroup()

index_diff <- dat$diff > 1e5
index_diff <- which(x = index_diff)

dat <- map(
  .x = index_diff,
  .f = function(x) {
    dat[x, ] |>
      mutate(
        startpos = endpos + 1,
        endpos = dat[x + 1, ]$startpos - 1
      )
  }
) |>
  bind_rows(dat)

ramp_loss_func <- scales::colour_ramp(c("blue", "white"))
ramp_gain_func <- scales::colour_ramp(c("white", "red"))
# add 1 to include white
ramp_loss <- ramp_loss_func(x = seq(0, 1, length = 3)) |>
  head(-1)
ramp_gain <- ramp_gain_func(x = seq(0, 1, length = 9)) |>
  tail(-1)

plot_snp <- map(
  .x = dat$line |> unique() |> sort(),
  .f = function(x) {
    dat |>
      filter(line == x) |>
      mutate(total = nMajor + nMinor) |>
      mutate(
        total = case_when(
          total > 10 ~ "> 10",
          .default = as.character(total)
        ),
      ) |>
      ggplot(
        mapping = aes(
          xmin = startpos,
          xmax = endpos,
          ymin = 0,
          ymax = 1,
          fill = total
        )
      ) +
      geom_rect(show.legend = TRUE) +
      scale_fill_manual(
        values = c(ramp_loss, "#ffffff", ramp_gain) |>
          set_names(nm = c(0:9) |> as.character(), "> 10"),
        breaks = c(c(0:9) |> as.character(), "> 10"),
        drop = FALSE
      ) +
      scale_x_continuous(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0)) +
      #  ggh4x::facet_nested_wrap(
      #    facets = vars(type, chr),
      #    dir = "h",
      #    strip.position = "left",
      #    axes = "all",
      #    remove_labels = "all"
      # ) +
      # theme(strip.placement = "outside")
      facet_grid(
        rows = vars(sample),
        cols = vars(chr),
        scales = "free",
        switch = "y"
      ) +
      theme(
        aspect.ratio = 1,
        panel.spacing.x = unit(0, "lines"),
        panel.spacing.y = unit(0, "lines"),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_text(angle = 0),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.25),
        strip.text.y.left = element_text(angle = 0)
      )
  }
)

plot_snp[[1]] + theme(legend.position = "none", strip.background = element_rect(fill = NA)) +
  ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")) +
  theme(
    strip.text.y = element_text(colour = "white"),
    strip.background.y = element_rect(fill = line_cols[1])
  )

patchwork::wrap_plots(
  plot_snp[[1]] +
    theme(legend.position = "none", strip.background = element_rect(fill = NA)) +
    ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")) +
    theme(strip.text.y = element_text(colour = "white"), strip.background.y = element_rect(fill = line_cols[1])),
  plot_snp[[2]] + 
    theme(legend.position = "none", strip.text.x.top = element_blank(), strip.background = element_rect(fill = NA)) + 
    ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")) +
    theme(strip.text.y = element_text(colour = "white"), strip.background.y = element_rect(fill = line_cols[2])),
  plot_snp[[3]] + theme(strip.text.x.top = element_blank(), strip.background = element_rect(fill = NA)) + guides(fill = guide_legend(title = "Abs. CN")) + 
    ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")) +
    theme(strip.text.y = element_text(colour = "white"), strip.background.y = element_rect(fill = line_cols[3])),
  plot_snp[[4]] + theme(legend.position = "none", strip.text.x.top = element_blank(), strip.background = element_rect(fill = NA)) + 
    ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")) +
    theme(strip.text.y = element_text(colour = "white"), strip.background.y = element_rect(fill = line_cols[4])) +
    theme(legend.key.height = unit(0.5, "cm"), legend.key.width = unit(0.5, "cm")),
  ncol = 1,
  guides = "collect"
)

ggsave(
  filename = here("btrg", "snp.pdf"),
  device = cairo_pdf,
  width = 17.5,
  height = 10,
  units = "cm"
)

plot_snp[[3]] +
  theme(strip.text.x.top = element_blank(), strip.background = element_rect(fill = NA))
```


```{r}
patchwork::wrap_plots(
  mds_plot +
    theme(legend.position = "none") +
    ggh4x::force_panelsizes(rows = unit(10, "cm"), cols = unit(10, "cm")),
  dist_plot +
    ggh4x::force_panelsizes(rows = unit(10, "cm"), cols = unit(10, "cm"))
)
ggsave(
  filename = here("btrg", "mds.pdf"),
  device = cairo_pdf,
  width = 50,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "mds.pdf"),
    here("btrg", "mds.pdf")
  ),
  stdout = NULL
)
patchwork::wrap_plots(
  all_umap + ggh4x::force_panelsizes(rows = unit(10, "cm"), cols = unit(10, "cm")),
  type_umap + ggh4x::force_panelsizes(rows = unit(10, "cm"), cols = unit(10, "cm"))
)
ggsave(
  filename = here("btrg", "integrated.pdf"),
  device = cairo_pdf,
  width = 50,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "integrated.pdf"),
    here("btrg", "integrated.pdf")
  ),
  stdout = NULL
)

numbat_umap
ggsave(
  filename = here("btrg", "numbat_umap.pdf"),
  device = cairo_pdf,
  width = 50,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "numbat_umap.pdf"),
    here("btrg", "numbat_umap.pdf")
  ),
  stdout = NULL
)

patchwork::wrap_plots(
  numbat_umap,
  patchwork::wrap_plots(
    patchwork::wrap_plots(
      mbp_umap,
      oligo_pie,
      ptprc_umap,
      immune_pie,
      nrow = 2
    )
  ),
  ncol = 4
)

ggsave(
  filename = here("btrg", "norm_compar.pdf"),
  device = cairo_pdf,
  width = 30,
  height = 20,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "norm_compar.pdf"),
    here("btrg", "norm_compar.pdf")
  ),
  stdout = NULL
)
```


```{r}
umap_all <- scater::runUMAP(sce_all)

plot_data_all <- reducedDim(
  x = umap,
  type = "UMAP"
) |>
  as_tibble(
    # rownames = "bc_wells",
    .name_repair = "unique"
  ) |>
  rename(UMAP_1 = 1, UMAP_2 = 2) |>
  cbind(
    colData(umap_all) |>
      as_tibble()
    # by = join_by(bc_wells)
  )

umap_all_plot <- plot_data_all |>
  slice(sample(1:n())) |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = UMAP_1,
      y = UMAP_2,
      colour = Line,
      fill = Line,
      shape = Sample
    )
  ) +
  geom_point(
    size = 2,
    key_glyph = "rect"
  ) +
  geom_point() +
  scale_colour_manual(values = line_cols) +
  scale_fill_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_legend(title = "Line"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  ) +
  ggh4x::force_panelsizes(
    rows = unit(10, "cm"),
    cols = unit(10, "cm")
  ) +
  ggtitle("All Samples")

ggsave(
  filename = here("btrg", "before_norm.pdf"),
  # plot = plot_dimred,
  device = cairo_pdf,
  width = 75,
  height = 75,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "before_norm.pdf"),
    here("btrg", "before_norm.pdf")
  ),
  stdout = NULL
)
```

<!-- ```{r} -->
<!-- sce_all <- purrr::reduce( -->
<!--   .x = sce_list, -->
<!--   .f = cbind -->
<!-- ) -->
<!-- reducedDim(sce_all, "X_scVI_UMAP") <- reducedDim(sce_scvi, "X_scVI_UMAP") -->

<!-- scater::plotReducedDim( -->
<!--   object = sce_all, -->
<!--   dimred = "X_scVI_UMAP", -->
<!--   colour_by = "TOP2A", -->
<!--   swap_rownames = "gene_name" -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r fin} -->
<!-- dimred_data <- reducedDim( -->
<!--   x = sce_scvi, -->
<!--   type = "X_scVI_MDE" -->
<!-- ) |> -->
<!--   as_tibble( -->
<!--     rownames = "bc_wells", -->
<!--     .name_repair = "unique" -->
<!--   ) |> -->
<!--   rename(X_scVI_MDE_1 = 2, X_scVI_MDE_2 = 3) -->

<!-- map( -->
<!--   .x = c("leiden", "PTPRC", "MBP"), -->
<!--   .f = function(x) { -->
<!--     if (x == "leiden") { -->
<!--       scater::plotReducedDim( -->
<!--         object = sce_scvi, -->
<!--         dimred = "X_scVI_MDE", -->
<!--         colour_by = x, -->
<!--         text_by = x -->
<!--       ) -->
<!--     } else { -->
<!--       scater::plotReducedDim( -->
<!--         object = sce_scvi, -->
<!--         dimred = "X_scVI_MDE", -->
<!--         colour_by = x, -->
<!--         swap_rownames = "gene_name" -->
<!--       ) -->
<!--     } -->
<!--   } -->
<!-- ) |> -->
<!--   patchwork::wrap_plots() + -->
<!--   theme(aspect.ratio = 1) -->


<!-- high_immune_cells <- dimred_data |> -->
<!--   filter(X_scVI_MDE_1 > 1.5 & X_scVI_MDE_2 < -2) |> -->
<!--   pull(bc_wells) -->
<!-- high_oligo_cells <- dimred_data |> -->
<!--   filter(X_scVI_MDE_1 > 2 & X_scVI_MDE_2 > -1) |> -->
<!--   pull(bc_wells) -->

<!-- norm_labels <- colData(sce_scvi) |> -->
<!--   as_tibble() |> -->
<!--   mutate( -->
<!--     class = case_when( -->
<!--       bc_wells %in% high_immune_cells | bc_wells %in% high_oligo_cells ~ "normal", -->
<!--       .default = "tumour" -->
<!--     ) -->
<!--   ) |> -->
<!--   select(bc_wells, class) -->
<!-- immune_labels <- colData(sce_scvi) |> -->
<!--   as_tibble() |> -->
<!--   mutate( -->
<!--     immune = case_when( -->
<!--       bc_wells %in% high_immune_cells ~ "immune", -->
<!--       .default = "non-immune" -->
<!--     ) -->
<!--   ) |> -->
<!--   select(bc_wells, immune) -->

<!-- write_rds( -->
<!--   x = norm_labels, -->
<!--   file = here("data", "processed", "3_1_norm_labels", "norm_labels.rds") -->
<!-- ) -->
<!-- write_csv( -->
<!--   x = norm_labels, -->
<!--   file = here("data", "processed", "3_1_norm_labels", "norm_labels.csv") -->
<!-- ) -->
<!-- write_rds( -->
<!--   x = immune_labels, -->
<!--   file = here("data", "processed", "3_1_norm_labels", "immune_labels.rds") -->
<!-- ) -->

<!-- table(norm_labels$class) -->
<!-- ``` -->

<!-- ```{r numbat, eval=FALSE, include=FALSE} -->
<!-- sce_all <- purrr::reduce( -->
<!--   .x = sce_list, -->
<!--   .f = cbind -->
<!-- ) -->
<!-- sce_all$bc_wells_corr <- colData(sce_all) |> -->
<!--   as_tibble() |> -->
<!--   mutate(bc_wells = str_replace(bc_wells, pattern = "__", replacement = "_")) |> -->
<!--   pull(bc_wells) -->

<!-- count_mat <- counts(sce_all) -->
<!-- colnames(count_mat) <- sce_all$bc_wells_corr -->
<!-- rownames(count_mat) <- rowData(sce_all)$gene_name -->

<!-- count_mat <- count_mat[!duplicated(rownames(count_mat)), ] -->

<!-- ref_internal_all <- numbat::aggregate_counts( -->
<!--   count_mat = count_mat, -->
<!--   annot = colData(sce_all) |> -->
<!--     as_tibble() |> -->
<!--     left_join( -->
<!--       y = norm_labels, -->
<!--       by = join_by(bc_wells) -->
<!--     ) |> -->
<!--     mutate(cell = bc_wells_corr, group = class) |> -->
<!--     select(cell, group), -->
<!--   normalized = TRUE -->
<!-- ) -->
<!-- ref_internal_immune <- numbat::aggregate_counts( -->
<!--   count_mat = count_mat, -->
<!--   annot = colData(sce_all) |> -->
<!--     as_tibble() |> -->
<!--     left_join( -->
<!--       y = immune_labels, -->
<!--       by = join_by(bc_wells) -->
<!--     ) |> -->
<!--     mutate(cell = bc_wells_corr, group = immune) |> -->
<!--     select(cell, group), -->
<!--   normalized = TRUE -->
<!-- ) -->

<!-- write_rds( -->
<!--   x = ref_internal_all, -->
<!--   file = here("data", "processed", "3_1_norm_labels", "all_norm_numbat_ref.rds") -->
<!-- ) -->
<!-- write_rds( -->
<!--   x = ref_internal_immune, -->
<!--   file = here("data", "processed", "3_1_norm_labels", "all_immune_numbat_ref.rds") -->
<!-- ) -->
<!-- ``` -->

# ```{r singler}
# source(here("eval", "scripts", "r", "load_ref_list.R"))
# source(here("eval", "scripts", "r", "singler_anno_func.R"))
# 
# ref_list <- load_ref_list()
# 
# test_list <- list(test = sce_scvi_norm)
# 
# assayNames(test_list$test) <- c("counts", "logcounts")
# 
# cell_labels <- singler_anno_func(
#   test_list = test_list,
#   ref_list = ref_list,
#   test_hvgs = list(test = rownames(test_list$test)),
#   ref_hvgs = list(couturier= rownames(test_list$test)),
#   per_cluster = FALSE
# )
# sce_scvi_norm$pred_single_labels <- cell_labels$pred[[1]]$labels
# 
# cluster_labels <- singler_anno_func(
#   test_list = test_list,
#   ref_list = ref_list,
#   test_hvgs = list(test = rownames(test_list$test)),
#   ref_hvgs = list(couturier= rownames(test_list$test)),
#   per_cluster = TRUE,
#   cluster_label = "leiden"
# )
# sce_scvi_norm$pred_cluster_labels <- colData(sce_scvi_norm) |>
#   as_tibble() |>
#   left_join(
#     y = cluster_labels$pred[[1]] |>
#       rename(leiden = cluster) |>
#       select(leiden, labels),
#     by = join_by(leiden)
#   ) |>
#   pull(labels)
# 
# mutate(
#     pred_cluster_labels =
#       case_when(
#         leiden %in% cluster_labels$pred[[1]]$cluster ~ cluster_labels$pred[[1]]$pruned.labels
#       )
#     )
# 
# patchwork::wrap_plots(
#   scater::plotReducedDim(
#  object = sce_scvi_norm[ , !sce_scvi_norm$line == "GL0028"],
#   dimred = "X_scVI_UMAP",
#   colour_by = "pred_single_labels"
# ) +
#   scale_y_reverse() +
#   scale_x_reverse() +
#   theme(aspect.ratio = 1),
# scater::plotReducedDim(
#   object = sce_scvi_norm[ , !sce_scvi_norm$line == "GL0028"],
#   dimred = "X_scVI_UMAP",
#   colour_by = "pred_cluster_labels"
# ) +
#   scale_y_reverse() +
#   scale_x_reverse() +
#   theme(aspect.ratio = 1)
# )

<!-- scvi_list <- imap( -->
<!--   .x = scvi_list, -->
<!--   .f = function(sce, i) { -->
<!--     # filter for each sample -->
<!--     filtered_tib <- cluster_labels |> -->
<!--       filter(test == i) -->
<!--     # for each reference -->
<!--     final_labels <- map( -->
<!--       .x = filtered_tib$ref, -->
<!--       .f = function(ref_unique) { -->
<!--         filtered_tib |> -->
<!--           filter(ref == ref_unique) |> -->
<!--           unnest(cols = "pred") |> -->
<!--           select(cluster, pruned.labels) |> -->
<!--           rename( -->
<!--             !!paste(ref_unique, "cluster_label", sep = "_") := pruned.labels -->
<!--           ) -->
<!--       } -->
<!--     ) |> -->
<!--       purrr::reduce(.f = left_join, by = "cluster") -->

<!--     colData(sce) <- colData(sce) |> -->
<!--       as_tibble() |> -->
<!--       left_join( -->
<!--         y = final_labels, -->
<!--         by = "cluster" -->
<!--       ) |> -->
<!--       DataFrame() -->

<!--     sce -->
<!--   } -->
<!-- ) -->

<!-- map( -->
<!--   .x = scvi_list, -->
<!--   .f = function(sce) { -->
<!--     map( -->
<!--       .x = c("sample", "leiden", "G2M", "couturier_cluster_label", "couturier_cell_label"), -->
<!--       .f = function(y) { -->
<!--         scater::plotReducedDim( -->
<!--           object = sce, -->
<!--           dimred = "UMAP", -->
<!--           colour_by = y -->
<!--         ) -->
<!--       } -->
<!--     ) |> -->
<!--       patchwork::wrap_plots() -->
<!--   } -->
<!-- ) -->

<!-- imap( -->
<!--   .x = scvi_list, -->
<!--   .f = function(sce, i) { -->
<!--     dat <- colData(sce) |> -->
<!--       as_tibble() |> -->
<!--       select(couturier_cluster_label, couturier_cell_label) -->

<!--     table(dat$couturier_cluster_label, dat$couturier_cell_label) |> -->
<!--       proportions() |> -->
<!--       as.data.frame() |> -->
<!--       as_tibble() |> -->
<!--       rename(cluster = 1, label = 2, prop = 3) |> -->
<!--       ggplot( -->
<!--         aes( -->
<!--           x = cluster, -->
<!--           y = prop, -->
<!--           fill = label -->
<!--         ) -->
<!--       ) + -->
<!--       geom_bar(position = "fill", stat = "identity") + -->
<!--       ggtitle(label = i) -->
<!--   } -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r colours} -->
<!-- # https://medialab.github.io/iwanthue/ -->
<!-- seed_cols <- c("#e47093", "#61c07f", "#a28ae1", "#c1a148") -->
<!-- sample_cols <- map( -->
<!--   .x = seed_cols, -->
<!--   .f = function(x) { -->
<!--     tinter::tinter( -->
<!--       x = x, -->
<!--       steps = 2 -->
<!--     ) -->
<!--   } -->
<!-- ) |> -->
<!--   unlist() |> -->
<!--   set_names(nm = sample_names) -->
<!-- ``` -->

<!-- ```{r normal_plot} -->
<!-- plot_data <- reducedDim( -->
<!--   x = sce_scvi, -->
<!--   type = "X_scVI_MDE" -->
<!-- ) |> -->
<!--   as_tibble( -->
<!--     rownames = "bc_wells", -->
<!--     .name_repair = "unique" -->
<!--   ) |> -->
<!--   rename(X_scVI_MDE_1 = 2, X_scVI_MDE_2 = 3) |> -->
<!--   left_join( -->
<!--     y = colData(sce_scvi) |> -->
<!--       as_tibble(), -->
<!--     by = join_by(bc_wells) -->
<!--   ) |> -->
<!--   left_join( -->
<!--     y = norm_labels, -->
<!--     by = join_by(bc_wells) -->
<!--   ) |> -->
<!--   left_join( -->
<!--     y = immune_labels, -->
<!--     by = join_by(bc_wells) -->
<!--   ) -->

<!-- plot_data <- plot_data |> -->
<!--   mutate( -->
<!--     high_immune = case_when( -->
<!--       bc_wells %in% high_immune_cells ~ "yes", -->
<!--       .default = "no" -->
<!--     ), -->
<!--     high_oligo = case_when( -->
<!--       bc_wells %in% high_oligo_cells ~ "yes", -->
<!--       .default = "no" -->
<!--     ) -->
<!--   ) |> -->
<!--   mutate( -->
<!--     ellipse = case_when( -->
<!--       high_immune == "yes" ~ "immune", -->
<!--       high_oligo == "yes" ~ "oligo" -->
<!--     ) -->
<!--   ) -->

<!-- plot_data <- plot_data |> -->
  <!-- left_join( -->
  <!--   y = logcounts(sce_all)[rowData(sce_all)$gene_name == "PTPRC", ] %>% -->
  <!--     as_tibble(rownames = "bc_wells") |> -->
  <!--     rename(PTPRC = value), -->
  <!--   by = join_by(bc_wells) -->
  <!-- ) |> -->
  <!-- left_join( -->
  <!--   y = logcounts(sce_all)[rowData(sce_all)$gene_name == "MBP", ] %>% -->
  <!--     as_tibble(rownames = "bc_wells") |> -->
  <!--     rename(MBP = value), -->
  <!--   by = join_by(bc_wells) -->
  <!-- ) -->

<!-- # norm_bc <- read_rds(file = here("data", "processed", "2_4_numbat_out", "GL0038_norm.rds")) -->
<!-- # plot_data <- plot_data |> -->
<!-- #   mutate( -->
<!-- #     numbat = case_when( -->
<!-- #       bc_wells %in% norm_bc ~ "yes", -->
<!-- #       .default = "no" -->
<!-- #     ) -->
<!-- #   ) -->

<!-- plot_data <- plot_data |> -->
<!--   mutate( -->
<!--     line = str_sub(sample, end = 6), -->
<!--     type = str_sub(sample, start = 8) -->
<!--   ) -->

<!-- # plot_data |> -->
<!-- #   ggplot( -->
<!-- #     mapping = aes( -->
<!-- #       x = X_scVI_MDE_1, -->
<!-- #       y = X_scVI_MDE_2, -->
<!-- #       colour = numbat, -->
<!-- #       shape = line -->
<!-- #     ) -->
<!-- #   ) + -->
<!-- #   geom_point() -->

<!-- plot_data |> -->
<!--   ggplot( -->
<!--     mapping = aes( -->
<!--       x = X_scVI_MDE_1, -->
<!--       y = X_scVI_MDE_2, -->
<!--       colour = sample, -->
<!--       shape = sample -->
<!--     ) -->
<!--   ) + -->
<!--   geom_point() + -->
<!--   # scale_colour_viridis_c() + -->
<!--   theme(aspect.ratio = 1) + -->
<!--   scale_colour_manual( -->
<!--     name = "sample", -->
<!--     labels = sample_names, -->
<!--     values = sample_cols -->
<!--   ) + -->
<!--   scale_shape_manual( -->
<!--     name = "sample", -->
<!--     labels = sample_names, -->
<!--     values = rep(c(15, 16, 17), times = 4) -->
<!--   ) + -->
<!--   ggforce::geom_mark_ellipse( -->
<!--     inherit.aes = FALSE, -->
<!--     mapping = aes( -->
<!--       x = X_scVI_MDE_1, -->
<!--       y = X_scVI_MDE_2, -->
<!--       group = ellipse, -->
<!--       filter = !is.na(ellipse) -->
<!--     ), -->
<!--     tol = 0.001, -->
<!--     expand = unit(2.5, "mm"), -->
<!--   ) + -->
<!--   ggh4x::force_panelsizes( -->
<!--     rows = unit(10, "cm"), -->
<!--     cols = unit(10, "cm") -->
<!--   ) -->

<!-- plot_data |> -->
<!--   ggplot( -->
<!--     mapping = aes( -->
<!--       x = X_scVI_MDE_1, -->
<!--       y = X_scVI_MDE_2, -->
<!--       colour = MBP, -->
<!--       # shape = sample -->
<!--     ) -->
<!--   ) + -->
<!--   geom_point() + -->
<!--   # scale_colour_viridis_c() + -->
<!--   theme(aspect.ratio = 1) + -->
<!--   # scale_colour_manual( -->
<!--   #   name = "sample", -->
<!--   #   labels = sample_names, -->
<!--   #   values = sample_cols -->
<!--   # ) + -->
<!--   # scale_shape_manual( -->
<!--   #   name = "sample", -->
<!--   #   labels = sample_names, -->
<!--   #   values = rep(c(15, 16, 17), times = 4) -->
<!--   # ) + -->
<!--   ggforce::geom_mark_ellipse( -->
<!--     inherit.aes = FALSE, -->
<!--     mapping = aes( -->
<!--       x = X_scVI_MDE_1, -->
<!--       y = X_scVI_MDE_2, -->
<!--       group = ellipse, -->
<!--       filter = !is.na(ellipse) -->
<!--     ), -->
<!--     tol = 0.001, -->
<!--     expand = unit(2.5, "mm"), -->
<!--   ) + -->
<!--   ggh4x::force_panelsizes( -->
<!--     rows = unit(10, "cm"), -->
<!--     cols = unit(10, "cm") -->
<!--   ) -->

<!-- plot_data |> -->
<!--   filter(!is.na(ellipse)) |> -->
<!--   group_by(sample, ellipse) |> -->
<!--   count() |> -->
<!--   group_by(ellipse) |> -->
<!--   mutate(percent = n / sum(n) * 100) |> -->
<!--   ggplot( -->
<!--     mapping = aes( -->
<!--       x = "", -->
<!--       y = percent, -->
<!--       fill = sample -->
<!--     ) -->
<!--   ) + -->
<!--   scale_fill_manual( -->
<!--     values = sample_cols, -->
<!--     drop = FALSE -->
<!--   ) + -->
<!--   geom_bar(stat = "identity", width = 1) + -->
<!--   coord_polar("y", start = 0) + -->
<!--   facet_wrap(~ellipse) + -->
<!--   theme( -->
<!--     aspect.ratio = 1, -->
<!--     axis.title.x = element_blank(), -->
<!--     axis.title.y = element_blank(), -->
<!--     panel.border = element_blank(), -->
<!--     panel.grid = element_blank(), -->
<!--     axis.ticks = element_blank(), -->
<!--     axis.text = element_blank() -->
<!--   ) + -->
<!--   ggh4x::force_panelsizes( -->
<!--     rows = unit(10, "cm"), -->
<!--     cols = unit(10, "cm") -->
<!--   ) -->

<!-- plot_data |> -->
<!--   filter(!is.na(ellipse)) |> -->
<!--   group_by(type, ellipse) |> -->
<!--   count() |> -->
<!--   group_by(ellipse) |> -->
<!--   mutate(percent = n / sum(n) * 100) |> -->
<!--   ggplot( -->
<!--     mapping = aes( -->
<!--       x = "", -->
<!--       y = percent, -->
<!--       fill = type -->
<!--     ) -->
<!--   ) + -->
<!--   # scale_fill_manual( -->
<!--   #   values = sample_cols, -->
<!--   #   drop = FALSE -->
<!--   # ) + -->
<!--   geom_bar(stat = "identity", width = 1) + -->
<!--   coord_polar("y", start = 0) + -->
<!--   facet_wrap(~ellipse) + -->
<!--   theme( -->
<!--     aspect.ratio = 1, -->
<!--     axis.title.x = element_blank(), -->
<!--     axis.title.y = element_blank(), -->
<!--     panel.border = element_blank(), -->
<!--     panel.grid = element_blank(), -->
<!--     axis.ticks = element_blank(), -->
<!--     axis.text = element_blank() -->
<!--   ) + -->
<!--   ggh4x::force_panelsizes( -->
<!--     rows = unit(10, "cm"), -->
<!--     cols = unit(10, "cm") -->
<!--   ) -->
```


<!-- ```{r} -->
<!-- tibble( -->
<!--   x = mds$x, -->
<!--   y = mds$y, -->
<!--   sample = colnames(bulk_counts_matrix) -->
<!-- ) |> -->
<!--   mutate( -->
<!--     line = str_sub(sample, end = 6), -->
<!--     type = str_sub(sample, start = 8) -->
<!--   ) |> -->
<!--   ggplot( -->
<!--     mapping = aes( -->
<!--       x = x, -->
<!--       y = y, -->
<!--       colour = line, -->
<!--       shape = type -->
<!--     ) -->
<!--   ) + -->
<!--   geom_jitter( -->
<!--     size = 5, -->
<!--     width = 100, -->
<!--     height = 100 -->
<!--   ) + -->
<!--   theme(aspect.ratio = 1) + -->
<!--   labs( -->
<!--     x = paste( -->
<!--       "var:", -->
<!--       { -->
<!--         100 * round(mds$var.explained[[1]], 3) -->
<!--       } |> as.character(), -->
<!--       "%" -->
<!--     ), -->
<!--     y = paste( -->
<!--       "var:", -->
<!--       { -->
<!--         100 * round(mds$var.explained[[2]], 3) -->
<!--       } |> as.character(), -->
<!--       "%" -->
<!--     ) -->
<!--   ) -->
<!-- # -->
<!-- # bulk_counts_tumour <- scuttle::summarizeAssayByGroup( -->
<!-- #   x = sce_all[ , colnames(sce_all) %in%  {norm_labels |> filter(class == "tumour") |> pull(bc_wells) }], -->
<!-- #   ids = colData(sce_all[ , colnames(sce_all) %in%  {norm_labels |> filter(class == "tumour") |> pull(bc_wells) }])$sample, -->
<!-- #   BPPARAM = MulticoreParam( -->
<!-- #     workers = length(parallelly::availableWorkers()) -->
<!-- #   ) -->
<!-- # ) -->
<!-- # bulk_counts_tumour_matrix <- assay(bulk_counts_tumour, "mean") |> -->
<!-- #   as.matrix() -->
<!-- # -->
<!-- # mds_tumour <- limma::plotMDS( -->
<!-- #   x = bulk_counts_tumour_matrix, -->
<!-- #   top = 5000 -->
<!-- # ) -->
<!-- # -->
<!-- # tibble( -->
<!-- #   x = mds_tumour$x, -->
<!-- #   y = mds_tumour$y, -->
<!-- #   sample = colnames(bulk_counts_tumour_matrix) -->
<!-- # ) |> -->
<!-- #   mutate( -->
<!-- #     line = str_sub(sample, end = 6), -->
<!-- #     type = str_sub(sample, start = 8) -->
<!-- #   ) |> -->
<!-- #   ggplot( -->
<!-- #     mapping = aes( -->
<!-- #       x = x, -->
<!-- #       y = y, -->
<!-- #       colour = line, -->
<!-- #       shape = type -->
<!-- #     ) -->
<!-- #   ) + -->
<!-- #   geom_point(size = 5) + -->
<!-- #   theme(aspect.ratio = 1) + -->
<!-- #   labs( -->
<!-- #     x = paste("var:", {100 * round(mds_tumour$var.explained[[1]], 3)} |>  as.character(), "%"), -->
<!-- #     y = paste("var:", {100 * round(mds_tumour$var.explained[[2]], 3)} |>  as.character(), "%") -->
<!-- #     ) -->
<!-- # -->
<!-- # -->
<!-- # bulk_counts_three <- scuttle::summarizeAssayByGroup( -->
<!-- #   x = sce_all[, colData(sce_all)$sample %notin% c("GL0128_PDN", "GL0128_PDO", "GL0128_T")], -->
<!-- #   ids = colData(sce_all[ , colData(sce_all)$sample %notin% c("GL0128_PDN", "GL0128_PDO", "GL0128_T")])$sample , -->
<!-- #   BPPARAM = MulticoreParam( -->
<!-- #     workers = length(parallelly::availableWorkers()) -->
<!-- #   ) -->
<!-- # ) -->
<!-- # bulk_counts_three_matrix <- assay(bulk_counts_three, "mean") |> -->
<!-- #   as.matrix() -->
<!-- # -->
<!-- # mds_three <- limma::plotMDS( -->
<!-- #   x = bulk_counts_three_matrix, -->
<!-- #   top = 5000 -->
<!-- # ) -->
<!-- # -->
<!-- # tibble( -->
<!-- #   x = mds_three$x, -->
<!-- #   y = mds_three$y, -->
<!-- #   sample = colnames(bulk_counts_three_matrix) -->
<!-- # ) |> -->
<!-- #   mutate( -->
<!-- #     line = str_sub(sample, end = 6), -->
<!-- #     type = str_sub(sample, start = 8) -->
<!-- #   ) |> -->
<!-- #   ggplot( -->
<!-- #     mapping = aes( -->
<!-- #       x = x, -->
<!-- #       y = y, -->
<!-- #       colour = line, -->
<!-- #       shape = type -->
<!-- #     ) -->
<!-- #   ) + -->
<!-- #   geom_point(size = 5) + -->
<!-- #   theme(aspect.ratio = 1) + -->
<!-- #   labs( -->
<!-- #     x = paste("var:", {100 * round(mds$var.explained[[1]], 3)} |>  as.character(), "%"), -->
<!-- #     y = paste("var:", {100 * round(mds$var.explained[[2]], 3)} |>  as.character(), "%") -->
<!-- #     ) -->
<!-- ``` -->




<!-- ```{r} -->
<!-- umap_res <- uwot::umap( -->
<!--   X = reducedDim(sce_scvi, "X_scVI"), -->
<!--   metric = "manhattan", -->
<!--   seed = 42, -->
<!--   n_threads = 40 -->
<!-- ) -->

<!-- umap_res <- umap_res |> -->
<!--   as_tibble(rownames = "bc_wells") |> -->
<!--   left_join( -->
<!--     y = colData(sce_scvi) |> -->
<!--       as_tibble(), -->
<!--     by = join_by(bc_wells) -->
<!--   ) -->

<!-- umap_res |> -->
<!--   ggplot( -->
<!--     mapping = aes( -->
<!--       x = V1, -->
<!--       y = V2, -->
<!--       colour = leiden -->
<!--     ) -->
<!--   ) + -->
<!--   geom_point() -->

<!-- sce_scvi <- scater::runUMAP( -->
<!--   x = sce_scvi, -->
<!--   dimred = "X_scVI", -->
<!--   BPPARAM = MulticoreParam( -->
<!--     workers = length(parallelly::availableWorkers()) -->
<!--   ) -->
<!-- ) -->

<!-- patchwork::wrap_plots( -->
<!--   scater::plotReducedDim( -->
<!--     object = sce_scvi, -->
<!--     dimred = "UMAP", -->
<!--     colour_by = "leiden", -->
<!--     text_by = "leiden" -->
<!--   ), -->
<!--   scater::plotReducedDim( -->
<!--     object = sce_scvi, -->
<!--     dimred = "UMAP", -->
<!--     colour_by = "sample" -->
<!--   ) -->
<!-- ) + -->
<!--   theme(aspect.ratio = 1) -->


<!-- cluster <- scran::clusterCells( -->
<!--   x = sce_scvi, -->
<!--   assay.type = NULL, -->
<!--   use.dimred = "X_scVI_MDE", -->
<!--   BLUSPARAM = bluster::DbscanParam() -->
<!--   # BPPARAM = MulticoreParam( -->
<!--   #   workers = length(parallelly::availableWorkers()) -->
<!--   # ) -->
<!-- ) -->

<!-- dist_res <- dist(x = reducedDim(sce_scvi, "UMAP")) -->
<!-- plot(a) -->

<!-- hbdscan_res <- dbscan::hdbscan( -->
<!--   x = reducedDim(sce_scvi, "X_scVI"), -->
<!--   minPts = 10 -->
<!-- ) -->

<!-- scater::plotReducedDim( -->
<!--     object = sce_scvi, -->
<!--     dimred = "UMAP", -->
<!--     colour_by = I(hbdscan_res$cluster) -->
<!--   ) -->
<!-- ``` -->

<!-- ` -->
