---
title: "4_tumour_only"
author: "zm"
date: "2024-07-17"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
set.seed(42)
```

```{r here}
library(here)
```

```{r libraries}
library(BiocParallel)
library(SingleCellExperiment)
library(tidyverse)

conflicted::conflict_prefer_all(winner = "dplyr", quiet = TRUE)
```

```{r names}
# extract names from folders
sample_names <- list.dirs(
  path = here("data", "raw", "splitpipe", "combined"),
  recursive = FALSE
) |>
  str_subset(pattern = "GL") |>
  basename()

sample_groups <- sample_names |>
  str_extract(
    pattern = "[^_]+"
  )

sample_list <- list(
  sample_names[1:3],
  sample_names[4:6],
  sample_names[7:9],
  sample_names[10:12]
) |>
  set_names(
    sample_groups[1],
    sample_groups[4],
    sample_groups[7],
    sample_groups[10],
  )
```

```{r sce}
sce_tumour <- zellkonverter::readH5AD(
  file = here("data", "processed", "4_1_tumour_broad", "tumour_only.h5ad")
)
```

```{r overall_dimred}
# line_cols <- c("#173f5f", "#3caea3", "#f6d55c", "#ed553b")
# # seed_cols <- c("#e47093", "#61c07f", "#a28ae1", "#c1a148")
# sample_cols <- map(
#   .x = line_cols,
#   .f = function(x) {
#     tinter::tinter(
#       x = x,
#       steps = 2
#     )
#   }
# ) |>
#   unlist() |>
#   set_names(nm = sample_names)
type_shapes <- c(16, 17, 15, 15) |> set_names(c("PDN", "PDO", "T", "TIS"))

ggplot2Colours <- function(n) {
  if (n %% 1 == 0 && n > 0) {
    hcl(h = seq(15, 375, length = n + 1), c = 100, l = 65)[1:n]
  } else {
    print("pos. int. req.")
  }
}
# pie_cols <- ggplot2Colours(n = 3) |>
#   set_names("PDN", "PDO", "TIS")

# cluster_cols <- Polychrome::kelly.colors(n = 8)[3:8] |>
#   set_names(c("Astro", "Mesenchymal", "Neuronal", "Oligo", "Progenitor", "Unassigned"))

source("/stornext/Bioinf/data/lab_brain_cancer/projects/pdo_pdn_comparison/analysis/scripts/r/annotation_colours.R")
# names(annotation_colours) <- case_when(
#   names(annotation_colours) == "AC-like" ~ "Astro",
#   names(annotation_colours) == "MES-like" ~ "Mesenchymal",
#   names(annotation_colours) == "OPC-like" ~ "Oligo",
#   names(annotation_colours) == "NPC-like" ~ "Neuronal",
#   names(annotation_colours) == "Unknown" ~ "Unassigned",
#   .default = names(annotation_colours)
# )
cluster_cols <- annotation_colours

plot_data <- reducedDim(
  x = sce_tumour,
  type = "X_scVI_MDE"
) |>
  as_tibble(
    rownames = "bc_wells",
    .name_repair = "unique"
  ) |>
  rename(MDE_1 = 2, MDE_2 = 3) |>
  left_join(
    y = colData(sce_tumour) |>
      as_tibble()
    # by = join_by(bc_wells)
  )

tumour_only_umap <- plot_data |>
  slice(sample(1:n())) |>
  mutate(Sample = type, Line = line) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = Line,
      fill = Line,
      shape = Sample
    )
  ) +
  geom_point(
    size = 1,
    key_glyph = "rect"
  ) +
  geom_point() +
  scale_colour_manual(values = line_cols) +
  scale_fill_manual(values = line_cols) +
  scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_legend(title = "Line"),
    shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  )
# ggh4x::force_panelsizes(
#   rows = unit(10, "cm"),
#   cols = unit(10, "cm")
# )
```

```{r singler}
source(here("eval", "scripts", "r", "load_ref_list.R"))
source(here("eval", "scripts", "r", "singler_anno_func.R"))

ref_list <- load_ref_list()

test_list <- list(test = sce_tumour)

# assayNames(test_list$test) <- c("counts", "logcounts")

cell_labels <- singler_anno_func(
  test_list = test_list,
  ref_list = ref_list,
  test_hvgs = list(test = rownames(test_list$test)),
  ref_hvgs = list(couturier = rownames(test_list$test)),
  per_cluster = FALSE
)
sce_tumour$pred_single_labels <- cell_labels$pred[[1]]$labels

cluster_labels <- singler_anno_func(
  test_list = test_list,
  ref_list = ref_list,
  test_hvgs = list(test = rownames(test_list$test)),
  ref_hvgs = list(couturier = rownames(test_list$test)),
  per_cluster = TRUE,
  cluster_label = "leiden"
)
sce_tumour$pred_cluster_labels <- colData(sce_tumour) |>
  as_tibble() |>
  left_join(
    y = cluster_labels$pred[[1]] |>
      rename(leiden = cluster) |>
      select(leiden, labels),
    by = join_by(leiden)
  ) |>
  pull(labels)

map(
  .x = cell_labels$pred,
  .f = function(x) {
    x |>
      select(bc_wells, labels)
  }
) |>
  bind_rows() |>
  write_csv(
    file = here("data", "processed", "4_1_tumour_broad", "singler_anno.csv")
  )

plot_data <- reducedDim(
  x = sce_tumour,
  type = "X_scVI_MDE"
) |>
  as_tibble(
    rownames = "bc_wells",
    .name_repair = "unique"
  ) |>
  rename(MDE_1 = 2, MDE_2 = 3) |>
  left_join(
    y = colData(sce_tumour) |>
      as_tibble()
    # by = join_by(bc_wells)
  )

plot_data <-plot_data |> 
  left_join(singler_anno) |> 
  mutate(pred_single_labels = labels)


plot_data <- plot_data |> 
  mutate(
    pred_single_labels = case_when(
      pred_single_labels == "Astro" ~ "AC-like",
      pred_single_labels == "Oligo" ~ "OPC-like",
      pred_single_labels == "Mesenchymal" ~ "MES-like",
      pred_single_labels == "Neuronal" ~ "NPC-like",
      pred_single_labels == "Unassigned" ~ "Unknown",
      .default = pred_single_labels
    )
    )

plot_umap_anno <- plot_data |>
  slice(sample(1:n())) |>
  mutate(Sample = type, Line = line, State = pred_single_labels) |>
  ggplot(
    mapping = aes(
      x = MDE_1,
      y = MDE_2,
      colour = State,
      fill = State
      # shape = Sample
    )
  ) +
  geom_point(
    size = 1,
    key_glyph = "rect"
  ) +
  geom_point() +
  scale_colour_manual(values = cluster_cols) +
  scale_fill_manual(values = cluster_cols) +
  # scale_shape_manual(values = type_shapes) +
  guides(
    colour = guide_legend(title = "State")
    # shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  theme(
    aspect.ratio = 1,
    axis.ticks = element_line(colour = "black"),
    axis.text = element_blank(),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90"),
    panel.background = element_rect(fill = "white", colour = "black")
  ) + 
  ggtitle("\nAll Samples - Tumour Cells")

plot_umap_anno

source("/vast/scratch/users/moore.z/pdo_pdn_comparison/eval/scripts/r/modify_facet_appearance.R")
plot_bar_anno <-
  plot_data |>
  filter(!line == "GL0128") |> 
  mutate(Sample = type, Line = line, State = pred_single_labels) |>
  mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
  ggplot(
    mapping = aes(
      x = Sample,
      # y = type,
      fill = State
    )
  ) +
  geom_bar(position = "fill") +
  # geom_bar(stat = "identity") +
  facet_grid(~Line) +
  scale_fill_manual(values = cluster_cols) +
  guides(
    colour = guide_legend(title = "State")
    # shape = guide_legend(title = "Sample", override.aes = list(size = 3))
  ) +
  scale_y_continuous(labels = scales::percent_format(), expand = c(0, 0)) +
  ylab("Percent") +
  theme(
    aspect.ratio = 3,
    axis.ticks = element_line(colour = "black"),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_line(colour = "grey90"),
    strip.background = element_rect(fill = "white", colour = "black"),
    panel.background = element_rect(fill = "white", colour = "black")
  )
# } %>%
# modify_facet_appearance(
#   plot = .,
#   strip.background.x.col = line_cols,
#   strip.text.x.col = line_cols
# )
plot(plot_bar_anno)

patchwork::wrap_plots(
  plot_umap_anno + theme(legend.position = "none") + ggh4x::force_panelsizes(cols = unit(10, "cm"), rows = unit(10, "cm")),
  plot_bar_anno
)
ggsave(
  filename = here("btrg", "all_states.pdf"),
  device = cairo_pdf,
  width = 27.5,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "all_states.pdf"),
    here("btrg", "all_states.pdf")
  ),
  stdout = NULL
)

patchwork::wrap_plots(
  scater::plotReducedDim(
    object = sce_tumour,
    dimred = "X_scVI_MDE",
    colour_by = "pred_single_labels"
  ) +
    theme(aspect.ratio = 1),
  scater::plotReducedDim(
    object = sce_tumour,
    dimred = "X_scVI_MDE",
    colour_by = "pred_cluster_labels"
  ) +
    theme(aspect.ratio = 1)
)
```

```{r deg_broad}
deg_list <- list(
  de_pdn_t = read_csv(
    file = here("data", "processed", "4_1_tumour_broad", "pdn_t.csv"),
    show_col_types = FALSE
  ),
  de_pdo_t = read_csv(
    file = here("data", "processed", "4_1_tumour_broad", "pdo_t.csv"),
    show_col_types = FALSE
  )
)

deg_list <- map(
  .x = deg_list,
  .f = function(x) {
    x |>
      rename(gene_id = 1) |>
      left_join(
        y = rowData(sce_tumour) |>
          as_tibble() |>
          select(gene_id, gene_name),
        by = join_by(gene_id)
      ) |>
      relocate(gene_name)
  }
)

volcano_plots <- imap(
  .x = deg_list,
  .f = function(x, i) {
    # big boilerplate energy
    up_lfc <- x |>
      filter(lfc_mean > 2) |>
      pull(gene_name)
    down_lfc <- x |>
      filter(lfc_mean < -2) |>
      pull(gene_name)
    up_sig_label <- x |>
      mutate(
        rank = bayes_factor * lfc_mean
      ) |>
      arrange(-rank) |>
      slice_head(n = 5) |>
      pull(gene_name)
    down_sig_label <- x |>
      mutate(
        rank = bayes_factor * lfc_mean
      ) |>
      arrange(rank) |>
      slice_head(n = 5) |>
      pull(gene_name)

    x <- x |>
      mutate(
        sig = case_when(
          gene_name %in% up_lfc & is_de_fdr_0.05 == TRUE ~ "up_sig",
          gene_name %in% down_lfc & is_de_fdr_0.05 == TRUE ~ "down_sig"
        )
      ) |>
      mutate(
        colour_point = case_when(
          sig == "up_sig" ~ "#BC3D41",
          sig == "down_sig" ~ "#4F7EBB",
          .default = "grey"
        )
      ) |>
      mutate(
        label_point = case_when(
          gene_name %in% c(up_sig_label, down_sig_label) ~ gene_name,
          .default = NA_character_
        )
      )

    if (i == "de_pdn_t") {
      title_up <- "<span style='color:#BC3D41;'>Up in PDN &rarr;</span>"
    } else if (i == "de_pdo_t") {
      title_up <- "<span style='color:#BC3D41;'>Up in PDO &rarr;</span>"
    }

    library(ggtext)
    # plot
    x |>
      ggplot(
        aes(
          x = lfc_mean,
          y = bayes_factor,
          colour = colour_point,
          label = label_point,
          shape = is_de_fdr_0.05
        )
      ) +
      geom_point(show.legend = FALSE) +
      scale_colour_identity() +
      labs(
        y = "Bayes Factor",
        x = expression("log"[2] * "FC")
      ) +
      theme(
        aspect.ratio = 1,
        panel.background = element_rect(fill = NA, colour = "black"),
        panel.grid = element_line(colour = "grey90"),
        # plot.title = element_text(hjust = 0.5)
        plot.title = ggtext::element_markdown(hjust = 0.5)
      ) +
      geom_hline(
        yintercept = x |> filter(is_de_fdr_0.05 == FALSE) |> slice(1) |> pull(bayes_factor),
        linetype = "dashed"
      ) +
      geom_vline(
        xintercept = c(-2, 2),
        linetype = "dashed"
      ) +
      coord_fixed(clip = "off") +
      # ggtitle(
      #   "Up in T Up in PDN"
      # ) +
      annotate(
        label = title_up,
        geom = "richtext",
        colour = "white",
        # label.padding = unit(c(0, 0, 0, 0), "lines"),
        x = Inf,
        y = Inf,
        vjust = -0.1,
        hjust = 1
      ) +
      annotate(
        label = "<span style='color:#4F7EBB;;'> &larr; Up in TIS </span>",
        geom = "richtext",
        colour = "white",
        # label.padding = unit(c(0, 0, 0, 0), "lines"),
        x = -Inf,
        y = Inf,
        vjust = -0.1,
        hjust = 0
      ) +
      labs(title = "", subtitle = "") +
      ggrepel::geom_label_repel(
        max.overlaps = 25,
        force = 2,
        size = 10 / .pt,
        fontface = "italic"
      )
    # ggh4x::force_panelsizes(
    #   rows = unit(7.5, "cm"),
    #   cols = unit(7.5, "cm")
    # )
  }
)

rrho <- RRHO2::RRHO2_initialize(
  list1 = deg_list$de_pdn_t |>
    # mutate(val = bayes_factor) |>
    mutate(val = -log10(bayes_factor) * (lfc_mean)) |>
    # filter(group1 == unique(diff$group1)[1]) |>
    select(gene_name, val) |>
    mutate(val = jitter(val)) |>
    distinct(gene_name, .keep_all = TRUE) |>
    as.data.frame(),
  list2 = deg_list$de_pdo_t |>
    # mutate(val = bayes_factor) |>
    mutate(val = -log10(bayes_factor) * (lfc_mean)) |>
    # filter(group1 == unique(diff$group1)[2]) |>
    select(gene_name, val) |>
    mutate(val = jitter(val)) |>
    distinct(gene_name, .keep_all = TRUE) |>
    as.data.frame(),
  # BY = TRUE,
  # boundary = 0.1
  # log10.ind = TRUE,
  # stepsize = 50,
  # alternative = "two.sided"
  # method = "fisher"
  multipleTesting = "none"
)

RRHO2::RRHO2_heatmap(rrho)


rrho_plot <- lattice::levelplot(
  x = rrho$hypermat,
  xlab = "pdn vs. tis",
  ylab = "pdo vs. tis"
)
rrho_plot

# names(rrho$hypermat) <- paste("X", 1:ncol(rrho$hypermat))

hypermat <- rrho$hypermat |>
  as_tibble()

rrho_plot <- hypermat |>
  rownames_to_column(var = "var1") |>
  pivot_longer(
    cols = -var1, names_to = "var2", values_to = "value"
  ) |>
  mutate(
    var1 = factor(var1, levels = 1:ncol(rrho$hypermat)),
    var2 = factor(gsub("V", "", var2), levels = 1:ncol(rrho$hypermat))
  ) |>
  ggplot(
    mapping =
      aes(
        x = var1,
        y = var2,
        fill = value
      )
  ) +
  geom_tile() +
  scale_fill_viridis_c(na.value = "white") +
  labs(
    x = "<span style='color:#4F7EBB;'>&larr; Up in TIS</span>
        <span style='color:#BC3D41;'>Up in PDN &rarr;</span>",
    y = "<span style='color:#4F7EBB;'>&larr; Up in TIS</span>
        <span style='color:#BC3D41;'>Up in PDO &rarr;</span>",
    fill = expression("-log"[10] * "p")
  ) +
  theme(
    aspect.ratio = 1,
    axis.text = element_blank(),
    axis.title.y = ggtext::element_markdown(vjust = 0.5),
    axis.title.x = ggtext::element_markdown(hjust = 0.5),
    axis.ticks = element_blank()
  )
# ggh4x::force_panelsizes(
#   rows = unit(7.5, "cm"),
#   cols = unit(7.5, "cm")
# )

patchwork::wrap_plots(
  volcano_plots$de_pdn_t,
  volcano_plots$de_pdo_t,
  rrho_plot
)
ggsave(
  filename = here("btrg", "broad_deg.pdf"),
  device = cairo_pdf,
  width = 30,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "broad_deg.pdf"),
    here("btrg", "broad_deg.pdf")
  ),
  stdout = NULL
)

enrich_broad <- map(
  .x = deg_list,
  .f = function(x) {
    library(enrichR)

    up_genes <- x |>
      filter(lfc_mean > 0) |>
      filter(is_de_fdr_0.05 == TRUE) |>
      pull(gene_name) |>
      as.character()
    down_genes <- x |>
      filter(lfc_mean < 0) |>
      filter(is_de_fdr_0.05 == TRUE) |>
      pull(gene_name) |>
      as.character()

    up_res <- enrichR::enrichr(
      genes = up_genes,
      databases = c(
        "GO_Molecular_Function_2018",
        "KEGG_2013",
        "Reactome_2013"
      )
    )
    down_res <- enrichR::enrichr(
      genes = down_genes,
      databases = c(
        "GO_Molecular_Function_2018",
        "KEGG_2013",
        "Reactome_2013"
      )
    )
    list(
      up = up_res,
      down = down_res
    )
  }
)

plot_enrich <- imap(
  .x = enrich_broad,
  .f = function(x, i) {
    if (i == "de_pdn_t") {
      title_up <- "<span style='color:#BC3D41;'>Up in PDN</span>"
      title_down <- "<span style='color:#4F7EBB;'>Up in TIS</span>"
    } else if (i == "de_pdo_t") {
      title_up <- "<span style='color:#BC3D41;'>Up in PDO</span>"
      title_down <- "<span style='color:#4F7EBB;'>Up in TIS</span>"
    }

    up_plot <- enrichR::plotEnrich(
      df = x$up$GO_Molecular_Function_2018,
      orderBy = "Combined.Score",
      showTerms = 15
    ) +
      scale_fill_viridis_c() +
      guides(fill = guide_colorbar(title = "Score")) +
      ggtitle(
        title_up
      ) +
      theme(
        aspect.ratio = 1,
        axis.title.y = element_blank(),
        plot.title = ggtext::element_markdown()
      )
    # ggh4x::force_panelsizes(
    #   rows = unit(5, "cm"),
    #   cols = unit(10, "cm")
    # )
    down_plot <- enrichR::plotEnrich(
      df = x$down$GO_Molecular_Function_2018,
      orderBy = "Combined.Score",
      showTerms = 15
    ) +
      scale_fill_viridis_c() +
      guides(fill = guide_colorbar(title = "Score")) +
      ggtitle(
        title_down
      ) +
      theme(
        aspect.ratio = 1,
        axis.title.y = element_blank(),
        plot.title = ggtext::element_markdown()
      )
    # ggh4x::force_panelsizes(
    #   rows = unit(5, "cm"),
    #   cols = unit(10, "cm")
    # )
    list(up = up_plot, down = down_plot)
  }
)
patchwork::wrap_plots(
  patchwork::wrap_plots(
    plot_enrich$de_pdn_t, plot_enrich$de_pdn_t,
    ncol = 1
  ),
  patchwork::wrap_plots(
    plot_enrich$de_pdo_t, plot_enrich$de_pdo_t,
    ncol = 1
  )
)
ggsave(
  filename = here("btrg", "broad_enrich.pdf"),
  device = cairo_pdf,
  width = 30,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "broad_enrich.pdf"),
    here("btrg", "broad_enrich.pdf")
  ),
  stdout = NULL
)
```

```{r scvi_res}
sce_scvi_list <- unique(sample_groups) |>
  set_names() |>
  map(
    .x = ,
    .f = function(x) {
      zellkonverter::readH5AD(
        file = here("data", "processed", "2_5_tumour_only", paste0(x, "_tumour_scvi.h5ad"))
      )
    }
  )

sce_scvi_list <- map(
  .x = sce_scvi_list,
  .f = function(sce) {
    sce$line <- str_sub(sce$sample, end = 6)
    sce$type <- str_sub(sce$sample, start = 8)
    sce
  }
)

graph_data <- names(sce_scvi_list) |>
  set_names() |>
  map(
    .f = function(x) {
      # should turn this into a data.table
      list(
        dist = read_csv(
          file = here("data", "processed", "2_5_tumour_only", paste0(x, "_dist.csv")),
          show_col_types = FALSE
        ),
        conn = read_csv(
          file = here("data", "processed", "2_5_tumour_only", paste0(x, "_con.csv")),
          show_col_types = FALSE
        )
      )
    }
  )
```

```{r singler}
source(here("eval", "scripts", "r", "load_ref_list.R"))
source(here("eval", "scripts", "r", "singler_anno_func.R"))

ref_list <- load_ref_list()

# use hvgs from scvi
test_hvgs <- map(
  .x = sce_scvi_list,
  .f = function(sce) {
    rownames(sce)
  }
)

cell_labels <- singler_anno_func(
  test_list = sce_scvi_list,
  ref_list = ref_list,
  test_hvgs = test_hvgs,
  ref_hvgs = test_hvgs,
  per_cluster = FALSE
)
sce_scvi_list <- imap(
  .x = sce_scvi_list,
  .f = function(sce, i) {
    # filter for each sample
    filtered_tib <- cell_labels |>
      filter(test == i)
    # for each reference
    final_labels <- map(
      .x = filtered_tib$ref,
      .f = function(ref_unique) {
        filtered_tib |>
          filter(ref == ref_unique) |>
          unnest(cols = "pred") |>
          select(bc_wells, labels) |>
          rename(
            !!paste(ref_unique, "cell_label", sep = "_") := labels
          )
      }
    ) |>
      purrr::reduce(.f = left_join, by = "bc_wells")

    colData(sce) <- colData(sce) |>
      as_tibble() |>
      left_join(
        y = final_labels,
        by = "bc_wells"
      ) |>
      DataFrame()

    sce
  }
)
cluster_labels <- singler_anno_func(
  test_list = sce_scvi_list,
  ref_list = ref_list,
  test_hvgs = test_hvgs,
  ref_hvgs = test_hvgs,
  per_cluster = TRUE,
  cluster_label = "leiden"
)
sce_scvi_list <- imap(
  .x = sce_scvi_list,
  .f = function(sce, i) {
    # filter for each sample
    filtered_tib <- cluster_labels |>
      filter(test == i)
    # for each reference
    final_labels <- map(
      .x = filtered_tib$ref,
      .f = function(ref_unique) {
        filtered_tib |>
          filter(ref == ref_unique) |>
          unnest(cols = "pred") |>
          select(cluster, labels) |>
          rename(
            leiden = cluster,
            !!paste(ref_unique, "cluster_label", sep = "_") := labels
          )
      }
    ) |>
      purrr::reduce(.f = left_join, by = "cluster")

    colData(sce) <- colData(sce) |>
      as_tibble() |>
      left_join(
        y = final_labels,
        by = "leiden"
      ) |>
      DataFrame()

    sce
  }
)

map(
  .x = sce_scvi_list,
  .f = function(sce) {
    map(
      .x = c("sample", "leiden", "couturier_cluster_label", "couturier_cell_label"),
      .f = function(y) {
        scater::plotReducedDim(
          object = sce,
          dimred = "X_scVI_MDE",
          colour_by = y
        )
      }
    ) |>
      patchwork::wrap_plots()
  }
)

distance_list <- imap(
  .progress = TRUE,
  .x = sce_scvi_list,
  .f = function(sce, i) {
    col_data <- colData(sce) |>
      as_tibble()

    dist <- graph_data[[i]]$dist
    conn <- graph_data[[i]]$conn
    colnames(dist) <- c("bc_wells", sce$bc_wells)
    dist <- dist |> select(-1)
    dist <- as.matrix(dist)
    rownames(dist) <- colnames(dist)

    col_data$couturier_cell_label |>
      unique() |>
      set_names() |>
      map(
        .f = function(x) {
          filt_col_data <- col_data |>
            filter(couturier_cell_label == x)

          c("PDN", "PDO") |>
            set_names() |>
            map(
              .f = function(y) {
                tis_wells <- filt_col_data |>
                  filter(type == "T") |>
                  pull(bc_wells)
                ref_wells <- filt_col_data |>
                  filter(type == y) |>
                  pull(bc_wells)

                # if(lengthtis_wells )

                dist_tib <- dist[tis_wells, ref_wells] |>
                  as_tibble(rownames = "tiss") |>
                  pivot_longer(
                    cols = -tiss,
                    names_to = "ref",
                    values_to = "distance"
                  )

                dist_tib
              }
            )
        }
      )
  }
)

distance_aggregate <- imap(
  .x = distance_list,
  .f = function(x, i) {
    imap(
      .x = x,
      .f = function(y, j) {
        imap(
          .x = y,
          .f = function(z, k) {
            z |>
              group_by(ref) |>
              summarise(
                mean = mean(distance),
                min = min(distance)
              ) |>
              mutate(
                sample = i,
                cluster = j,
                type = k
              )
          }
        ) |>
          bind_rows()
      }
    ) |>
      bind_rows()
  }
)

distance_plots <- imap(
  .x = distance_aggregate,
  .f = function(x, i) {
    plot_cols <- sample_cols[str_detect(
      string = names(sample_cols),
      pattern = paste(
        paste(x$sample, x$type, sep = "_") |>
          unique(),
        collapse = "|"
      )
    )] |>
      set_names(c("PDN", "PDO"))

    res <- aov(mean ~ cluster * type, data = x)
    summary(res)
    res_tuk <- TukeyHSD(res)

    a <- rownames(res_tuk$`cluster:type`)
    b <- str_split(string = a, pattern = "-") |>
      map(
        .f = function(x) {
          str_sub(string = x, end = -5)
        }
      )

    comparison_index <- map_vec(
      .x = b,
      .f = function(y) {
        identical(y[[1]], y[[2]])
      }
    )


    stat_tib <- res_tuk$`cluster:type` |>
      as_tibble(rownames = "comparison")
    stat_tib <- stat_tib[comparison_index, ] |>
      mutate(State = str_extract(comparison, pattern = "[^:]*")) |>
      mutate(sig = case_when(`p adj` < 0.05 ~ TRUE)) |>
      mutate(adj_p = scales::scientific(`p adj`, digits = 2))

    stat_tib <- stat_tib |>
      mutate(
        y_val = map_vec(
          .x = stat_tib$State,
          .f = function(y) {
            x |>
              filter(cluster == y) |>
              pull(mean) |>
              max()
          }
        )
      ) |>
      mutate(y_val = y_val * 1.05)

    highest <- x |>
      filter(mean == max(mean))
    if (highest$cluster %in% {
      stat_tib |>
        filter(sig == TRUE) |>
        pull(State)
    }) {
      ymax <- max(x$mean) * 1.1
    } else {
      ymax <- max(x$mean)
    }

    x |>
      mutate(Sample = type, State = cluster) |>
      mutate(Sample = case_when(Sample == "T" ~ "TIS", .default = Sample)) |>
      ggplot(
        mapping = aes(
          x = State,
          y = mean,
          colour = State,
          shape = Sample,
          fill = Sample
        )
      ) +
      geom_violin(adjust = 1, linewidth = 1.5) +
      scale_colour_manual(values = cluster_cols) +
      scale_fill_manual(values = plot_cols) +
      labs(
        y = "Average Distance from Tissue (A.U)",
        colour = "State"
      ) +
      geom_errorbar(
        inherit.aes = FALSE,
        data = stat_tib |>
          filter(sig == TRUE),
        mapping = aes(
          x = State,
          ymin = y_val,
          ymax = y_val
        ),
        linewidth = 0.5
      ) +
      geom_text(
        inherit.aes = FALSE,
        data = stat_tib |>
          filter(sig == TRUE) |>
          mutate(label = paste("adj.p =", adj_p)),
        mapping = aes(
          x = State,
          y = y_val,
          label = label
        ),
        size = 10 / .pt,
        vjust = -0.5
      ) +
      guides(fill = guide_legend(override.aes = list(linewidth = 0))) +
      ylim(
        c(
          min(x$mean) * 1.1,
          ymax
        )
      ) +
      # ggtitle(i) +
      theme(
        # aspect.ratio = 1 / 2,
        axis.ticks = element_line(colour = "black"),
        axis.title.x = element_blank(),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.background = element_rect(fill = "white", colour = "black")
      )
    # ggforce::geom_sina(size = 0.1) +
  }
)
distance_plots$GL0095

umap_plots <- imap(
  .x = sce_scvi_list,
  .f = function(sce, i) {
    plot_data <- reducedDim(
      x = sce,
      type = "X_scVI_MDE"
    ) |>
      bind_cols(sce$bc_wells) |>
      rename(MDE_1 = 1, MDE_2 = 2, bc_wells = 3) |>
      left_join(
        y = colData(sce) |>
          as_tibble()
        # by = join_by(bc_wells)
      )


    plot_cols <- sample_cols[names(sample_cols) %in% {
      plot_data$sample |> unique()
    }] |>
      set_names(c("PDN", "PDO", "T"))

    plot_data |>
      slice(sample(1:n())) |>
      mutate(Sample = type, Line = line) |>
      ggplot(
        mapping = aes(
          x = MDE_1,
          y = MDE_2,
          colour = Sample,
          # fill = Line,
          shape = Sample
        )
      ) +
      geom_point(
        size = 2,
        key_glyph = "rect"
      ) +
      geom_point() +
      scale_colour_manual(values = plot_cols) +
      scale_fill_manual(values = line_cols) +
      scale_shape_manual(values = type_shapes) +
      guides(
        colour = guide_legend(title = "Sample"),
        shape = guide_legend(title = "Sample", override.aes = list(size = 3))
      ) +
      theme(
        aspect.ratio = 1,
        axis.ticks = element_line(colour = "black"),
        axis.text = element_blank(),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.background = element_rect(fill = "white", colour = "black")
      )
  }
)
umap_plots_state <- imap(
  .x = sce_scvi_list,
  .f = function(sce, i) {
    plot_data <- reducedDim(
      x = sce,
      type = "X_scVI_MDE"
    ) |>
      bind_cols(sce$bc_wells) |>
      rename(MDE_1 = 1, MDE_2 = 2, bc_wells = 3) |>
      left_join(
        y = colData(sce) |>
          as_tibble()
        # by = join_by(bc_wells)
      )


    plot_cols <- sample_cols[names(sample_cols) %in% {
      plot_data$sample |> unique()
    }] |>
      set_names(c("PDN", "PDO", "T"))

    plot_data |>
      slice(sample(1:n())) |>
      mutate(Sample = type, Line = line, State = couturier_cell_label) |>
      ggplot(
        mapping = aes(
          x = MDE_1,
          y = MDE_2,
          colour = State,
          fill = State,
          shape = Sample
        )
      ) +
      geom_point(
        size = 2,
        key_glyph = "rect"
      ) +
      geom_point() +
      scale_colour_manual(values = cluster_cols) +
      scale_fill_manual(values = cluster_cols) +
      scale_shape_manual(values = type_shapes) +
      guides(
        colour = guide_legend(title = "State"),
        shape = guide_legend(title = "Sample", override.aes = list(size = 3))
      ) +
      theme(
        aspect.ratio = 1,
        axis.ticks = element_line(colour = "black"),
        axis.text = element_blank(),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.background = element_rect(fill = "white", colour = "black")
      )
  }
)
umap_plots_state
umap_plots$GL0095 +
  scale_colour_manual(values = pie_cols)
scale_shape_manual(values = c(16, 16, 16))

umap_examp <- scater::runUMAP(
  x = sce_scvi_list$GL0095,
  dimred = "X_scVI"
)
umap_examp$Sample <-
  case_when(
    umap_examp$sample == "GL0095_PDN" ~ "PDN",
    umap_examp$sample == "GL0095_PDO" ~ "PDO",
    umap_examp$sample == "GL0095_T" ~ "TIS"
  )
examp_plot <- scater::plotReducedDim(
  umap_examp,
  "UMAP",
  colour_by = "Sample",
  shape_by = "Sample"
) +
  theme_gray() + 
  guides(colour = guide_legend(title = "Sample")) +
  theme(
        aspect.ratio = 1,
        axis.ticks = element_line(colour = "black"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.background = element_rect(fill = "white", colour = "black")
      ) + 
  ggtitle("GL0095 - Tumour Only")

ggsave(
  plot = examp_plot + ggh4x::force_panelsizes(rows = unit(10, "cm"), cols = unit(10, "cm")),
  filename = here("btrg", "examp_umap.pdf"),
  device = cairo_pdf,
  width = 20,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "examp_umap.pdf"),
    here("btrg", "examp_umap.pdf")
  ),
  stdout = NULL
)


patchwork::wrap_plots(
  patchwork::wrap_plots(
    umap_plots$GL0095 + theme(legend.position = "none"),
    umap_plots_state$GL0095 + theme(legend.position = "none"),
    ncol = 1
    # guides = "collect"
  ),
  distance_plots$GL0095 + theme(aspect.ratio = 1 / 2)
  # guides = "collect"
)
distance_plots$GL0095 + ggtitle("GL0095") + theme(aspect.ratio = 1 / 2)
ggsave(
  filename = here("btrg", "dist_examp.pdf"),
  device = cairo_pdf,
  width = 20,
  height = 50,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "dist_examp.pdf"),
    here("btrg", "dist_examp.pdf")
  ),
  stdout = NULL
)

patchwork::wrap_plots(
  umap_plots$GL0095,
  umap_plots_state$GL0095 + guides(fill = "none", colour = "none"),
  distance_plots$GL0095 + theme(),
  nrow = 1,
  guides = "collect"
)
```

```{r}
# write_rds(
#   x = sce_scvi_list,
#   file = here("data", "processed", "2_6_tumour_only_anno", "sce_scvi_list.rds")
# )
# iwalk(
#   .x = sce_scvi_list,
#   .f = function(sce, i) {
#     library(zellkonverter)
#     zellkonverter::writeH5AD(
#       sce = sce,
#       file = here("data", "processed", "2_6_tumour_only_anno", paste0(i, "_tumour.h5ad")),
#       verbose = TRUE
#     )
# library(sceasy)
# sceasy::convertFormat(
#   obj = sce,
#   from = "sce",
#   to = "anndata",
#   outFile = here("data", "processed", "2_6_tumour_only_anno", paste0(i, "_tumour.h5ad"))
# )
# }
# )
```

```{r anno_deg}
deg_list_anno <- names(sce_scvi_list) |>
  set_names() |>
  map(
    .f = function(x) {
      list(
        de_pdn_t = read_csv(
          file = here("data", "processed", "2_7_tumour_deg_anno", paste0(x, "_pdn.csv")),
          show_col_types = FALSE
        ) |>
          dplyr::rename(gene_id = 1),
        de_pdo_t = read_csv(
          file = here("data", "processed", "2_7_tumour_deg_anno", paste0(x, "_pdo.csv")),
          show_col_types = FALSE
        ) |>
          dplyr::rename(gene_id = 1)
      )
    }
  )

volcano_plots_anno <- imap(
  .x = deg_list_anno,
  .f = function(x, i) {
    # per sample
    imap(
      .x = x,
      .f = function(y, j) {
        # per anno
        y$couturier_cell_label |>
          unique() |>
          set_names() |>
          map(
            .f = function(z) {
              dat <- y |>
                filter(couturier_cell_label == z)

              dat <- dat |>
                left_join(
                  y = sce_scvi_list[[i]] |>
                    rowData() |>
                    as_tibble() |>
                    select(gene_id, gene_name)
                )

              # big boilerplate energy
              up_lfc <- dat |>
                filter(lfc_mean > 2) |>
                pull(gene_name)
              down_lfc <- dat |>
                filter(lfc_mean < -2) |>
                pull(gene_name)
              up_sig_label <- dat |>
                mutate(
                  rank = bayes_factor * lfc_mean
                ) |>
                arrange(-rank) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                filter(lfc_mean > 2) |>
                slice_head(n = 5) |>
                pull(gene_name)
              down_sig_label <- dat |>
                mutate(
                  rank = bayes_factor * lfc_mean
                ) |>
                arrange(rank) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                filter(lfc_mean < -2) |>
                slice_head(n = 5) |>
                pull(gene_name)

              dat <- dat |>
                mutate(
                  sig = case_when(
                    gene_name %in% up_lfc & is_de_fdr_0.05 == TRUE ~ "up_sig",
                    gene_name %in% down_lfc & is_de_fdr_0.05 == TRUE ~ "down_sig"
                  )
                ) |>
                mutate(
                  colour_point = case_when(
                    sig == "up_sig" ~ "#BC3D41",
                    sig == "down_sig" ~ "#4F7EBB",
                    .default = "grey"
                  )
                ) |>
                mutate(
                  label_point = case_when(
                    gene_name %in% c(up_sig_label, down_sig_label) ~ gene_name,
                    .default = NA_character_
                  )
                )

              if (j == "de_pdn_t") {
                title_up <- "<span style='color:#BC3D41;'> Up in PDN &rarr;</span>"
              } else if (j == "de_pdo_t") {
                title_up <- "<span style='color:#BC3D41;'> Up in PDO &rarr;</span>"
              }

              # x_lim <- max(abs(dat$lfc_mean))

              library(ggtext)

              # plot
              dat |>
                ggplot(
                  aes(
                    x = lfc_mean,
                    y = bayes_factor,
                    colour = colour_point,
                    label = label_point,
                    shape = is_de_fdr_0.05
                  )
                ) +
                geom_point(show.legend = FALSE) +
                # scale_x_continuous(limits = c(-x_lim, x_lim)) +
                scale_colour_identity() +
                labs(
                  y = "Bayes Factor",
                  x = expression("log"[2] * "FC")
                ) +
                theme(
                  aspect.ratio = 1,
                  panel.background = element_rect(fill = NA, colour = "black"),
                  panel.grid = element_line(colour = "grey90"),
                  plot.title = element_text(size = 11),
                  plot.subtitle = element_text(size = 11)
                ) +
                geom_hline(
                  yintercept = dat |> filter(is_de_fdr_0.05 == FALSE) |> dplyr::slice(1) |> pull(bayes_factor),
                  linetype = "dashed"
                ) +
                geom_vline(
                  xintercept = c(-2, 2),
                  linetype = "dashed"
                ) +
                labs(
                  title = z,
                  subtitle = ""
                ) +
                coord_fixed(clip = "off") +
                annotate(
                  label = title_up,
                  geom = "richtext",
                  colour = "white",
                  # label.padding = unit(c(0, 0, 0, 0), "lines"),
                  x = Inf,
                  y = Inf,
                  vjust = -0.1,
                  hjust = 1
                ) +
                annotate(
                  label = "<span style='color:#4F7EBB;;'> &larr; Up in TIS </span>",
                  geom = "richtext",
                  colour = "white",
                  # label.padding = unit(c(0, 0, 0, 0), "lines"),
                  x = -Inf,
                  y = Inf,
                  vjust = -0.1,
                  hjust = 0
                ) +
                ggrepel::geom_label_repel(
                  max.overlaps = 25,
                  force = 2,
                  size = 10 / .pt
                )
              # patchwork::plot_annotation(
              #   title = title,
              #   theme = theme(plot.title = ggtext::element_markdown(hjust = 0.25))
              # )
            }
          )
      }
    )
  }
)
patchwork::wrap_plots(
  patchwork::wrap_plots(volcano_plots_anno$GL0128$de_pdn_t, nrow = 1),
  patchwork::wrap_plots(volcano_plots_anno$GL0128$de_pdo_t, nrow = 1),
  ncol = 1
)
ggsave(
  filename = here("btrg", "deg_anno_examp.pdf"),
  device = cairo_pdf,
  width = 50,
  height = 20,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "deg_anno_examp.pdf"),
    here("btrg", "deg_anno_examp.pdf")
  ),
  stdout = NULL
)

deg_venn_anno <- imap(
  .x = deg_list_anno[1:3],
  .f = function(x, i) {
    # per sample
    a <- imap(
      .x = x,
      .f = function(y, j) {
        # per anno
        y$couturier_cell_label |>
          unique() |>
          set_names() |>
          map(
            .f = function(z) {
              y |>
                filter(couturier_cell_label == z) |>
                filter(lfc_mean > 0) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                pull(gene_id)
            }
          )
      }
    )

    pmap(
      .l = list(
        pdn = a$de_pdn_t,
        pdo = a$de_pdo_t,
        names = names(a$de_pdo_t)
      ),
      .f = function(pdn, pdo, names) {
        list(
          PDN = pdn,
          PDO = pdo
        ) |>
          ggeulerr() +
          theme(
            panel.background = element_blank(),
            panel.grid = element_blank(),
            plot.title = element_text(size = 11),
            plot.subtitle = element_text(size = 11),
            axis.text = element_blank(),
            axis.title = element_blank(),
            axis.ticks = element_blank()
          ) +
          ggtitle(names) +
          scale_fill_manual(values = pie_cols)
        # library(ggVennDiagram)
        # ggVennDiagram::ggVennDiagram(
        #   x = list(
        #     PDN = pdn,
        #     PDO = pdo
        #   )
        # ) +
        #   scale_fill_viridis_c() +
        #   ggtitle(names) +
        #   guides(fill = guide_colorbar(title = "No. DEG Up"))
      }
    )
  }
)

patchwork::wrap_plots(
  patchwork::wrap_plots(deg_venn_anno$GL0028, nrow = 1, guides = "collect"),
  patchwork::wrap_plots(deg_venn_anno$GL0038, nrow = 1, guides = "collect"),
  patchwork::wrap_plots(deg_venn_anno$GL0095, nrow = 1, guides = "collect"),
  ncol = 1
)

enrich_deg_list_anno <- imap(
  .x = deg_list_anno,
  .f = function(x, i) {
    # per sample
    imap(
      .x = x,
      .f = function(y, j) {
        # per anno
        y$couturier_cell_label |>
          unique() |>
          set_names() |>
          map(
            .f = function(z) {
              filt <- y |>
                filter(couturier_cell_label == z) |>
                filter(lfc_mean > 0) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                left_join(
                  rowData(sce_scvi_list[[i]]) |>
                    as_tibble()
                )
              library(enrichR)
              enrichR::enrichr(
                genes = filt$gene_name |> as.character(),
                databases = "GO_Molecular_Function_2018"
              )
            }
          )
      }
    )
  }
)
enrich_deg_list_anno$GL0095$de_pdn_t$Progenitor |>
  as_tibble() |>
  View()
enrich_deg_list_anno$GL0095$de_pdo_t$Progenitor |>
  as_tibble() |>
  View()
volcano_plots_anno$GL0028
ggh4x::force_panelsizes(rows = unit(7.5, "cm"), cols = unit(7.5, "cm"))
volcano_plots_anno$GL0038$de_pdo_t$Astro +
  ggh4x::force_panelsizes(rows = unit(7.5, "cm"), cols = unit(7.5, "cm"))
```

```{r deg_per_anno_new}
deg_list_anno_new <- names(sce_scvi_list) |>
  set_names() |>
  map(
    .f = function(x) {
      list(
        de_pdn_t = read_csv(
          file = here("data", "processed", "4_1_tumour_broad", "pdn_t_per_sample_per_anno.csv"),
          show_col_types = FALSE
        ) |>
          dplyr::rename(gene_id = 1) |>
          filter(line == x),
        de_pdo_t = read_csv(
          file = here("data", "processed", "4_1_tumour_broad", "pdo_t_per_sample_per_anno.csv"),
          show_col_types = FALSE
        ) |>
          dplyr::rename(gene_id = 1) |>
          filter(line == x)
      )
    }
  )

volcano_plots_anno_new <- imap(
  .x = deg_list_anno_new,
  .f = function(x, i) {
    # per line
    imap(
      .x = x,
      .f = function(y, j) {
        # per anno
        y$labels |>
          unique() |>
          set_names() |>
          map(
            .f = function(z) {
              dat <- y |>
                filter(labels == z)

              dat <- dat |>
                left_join(
                  y = sce_tumour |>
                    rowData() |>
                    as_tibble() |>
                    select(gene_id, gene_name)
                )

              # big boilerplate energy
              up_lfc <- dat |>
                filter(lfc_mean > 2) |>
                pull(gene_name)
              down_lfc <- dat |>
                filter(lfc_mean < -2) |>
                pull(gene_name)
              up_sig_label <- dat |>
                mutate(
                  rank = bayes_factor * lfc_mean
                ) |>
                arrange(-rank) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                filter(lfc_mean > 2) |>
                slice_head(n = 5) |>
                pull(gene_name)
              down_sig_label <- dat |>
                mutate(
                  rank = bayes_factor * lfc_mean
                ) |>
                arrange(rank) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                filter(lfc_mean < -2) |>
                slice_head(n = 5) |>
                pull(gene_name)

              dat <- dat |>
                mutate(
                  sig = case_when(
                    gene_name %in% up_lfc & is_de_fdr_0.05 == TRUE ~ "up_sig",
                    gene_name %in% down_lfc & is_de_fdr_0.05 == TRUE ~ "down_sig"
                  )
                ) |>
                mutate(
                  colour_point = case_when(
                    sig == "up_sig" ~ "#BC3D41",
                    sig == "down_sig" ~ "#4F7EBB",
                    .default = "grey"
                  )
                ) |>
                mutate(
                  label_point = case_when(
                    gene_name %in% c(up_sig_label, down_sig_label) ~ gene_name,
                    .default = NA_character_
                  )
                )

              if (j == "de_pdn_t") {
                title_up <- "<span style='color:#BC3D41;'> Up in PDN &rarr;</span>"
              } else if (j == "de_pdo_t") {
                title_up <- "<span style='color:#BC3D41;'> Up in PDO &rarr;</span>"
              }

              # x_lim <- max(abs(dat$lfc_mean))

              library(ggtext)

              # plot
              dat |>
                ggplot(
                  aes(
                    x = lfc_mean,
                    y = bayes_factor,
                    colour = colour_point,
                    label = label_point,
                    shape = is_de_fdr_0.05
                  )
                ) +
                geom_point(show.legend = FALSE) +
                # scale_x_continuous(limits = c(-x_lim, x_lim)) +
                scale_colour_identity() +
                labs(
                  y = "Bayes Factor",
                  x = expression("log"[2] * "FC")
                ) +
                theme(
                  aspect.ratio = 1,
                  panel.background = element_rect(fill = NA, colour = "black"),
                  panel.grid = element_line(colour = "grey90"),
                  plot.title = element_text(size = 11),
                  plot.subtitle = element_text(size = 11)
                ) +
                geom_hline(
                  yintercept = dat |> filter(is_de_fdr_0.05 == FALSE) |> dplyr::slice(1) |> pull(bayes_factor),
                  linetype = "dashed"
                ) +
                geom_vline(
                  xintercept = c(-2, 2),
                  linetype = "dashed"
                ) +
                labs(
                  title = z,
                  subtitle = ""
                ) +
                coord_fixed(clip = "off") +
                annotate(
                  label = title_up,
                  geom = "richtext",
                  colour = "white",
                  # label.padding = unit(c(0, 0, 0, 0), "lines"),
                  x = Inf,
                  y = Inf,
                  vjust = -0.1,
                  hjust = 1
                ) +
                annotate(
                  label = "<span style='color:#4F7EBB;;'> &larr; Up in TIS </span>",
                  geom = "richtext",
                  colour = "white",
                  # label.padding = unit(c(0, 0, 0, 0), "lines"),
                  x = -Inf,
                  y = Inf,
                  vjust = -0.1,
                  hjust = 0
                ) +
                ggrepel::geom_label_repel(
                  max.overlaps = 25,
                  force = 2,
                  size = 10 / .pt
                )
              # patchwork::plot_annotation(
              #   title = title,
              #   theme = theme(plot.title = ggtext::element_markdown(hjust = 0.25))
              # )
            }
          )
      }
    )
  }
)
patchwork::wrap_plots(
  patchwork::wrap_plots(volcano_plots_anno_new$GL0095$de_pdn_t, nrow = 1),
  patchwork::wrap_plots(volcano_plots_anno_new$GL0095$de_pdo_t, nrow = 1),
  ncol = 1
)
ggsave(
  filename = here("btrg", "deg_anno_examp.pdf"),
  device = cairo_pdf,
  width = 50,
  height = 20,
  units = "cm"
)
system2(
  command = "pdfcrop",
  args = c(
    here("btrg", "deg_anno_examp.pdf"),
    here("btrg", "deg_anno_examp.pdf")
  ),
  stdout = NULL
)

deg_venn_anno <- imap(
  .x = deg_list_anno[1:3],
  .f = function(x, i) {
    # per sample
    a <- imap(
      .x = x,
      .f = function(y, j) {
        # per anno
        y$couturier_cell_label |>
          unique() |>
          set_names() |>
          map(
            .f = function(z) {
              y |>
                filter(couturier_cell_label == z) |>
                filter(lfc_mean > 0) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                pull(gene_id)
            }
          )
      }
    )

    pmap(
      .l = list(
        pdn = a$de_pdn_t,
        pdo = a$de_pdo_t,
        names = names(a$de_pdo_t)
      ),
      .f = function(pdn, pdo, names) {
        list(
          PDN = pdn,
          PDO = pdo
        ) |>
          ggeulerr() +
          theme(
            panel.background = element_blank(),
            panel.grid = element_blank(),
            plot.title = element_text(size = 11),
            plot.subtitle = element_text(size = 11),
            axis.text = element_blank(),
            axis.title = element_blank(),
            axis.ticks = element_blank()
          ) +
          ggtitle(names) +
          scale_fill_manual(values = pie_cols)
        # library(ggVennDiagram)
        # ggVennDiagram::ggVennDiagram(
        #   x = list(
        #     PDN = pdn,
        #     PDO = pdo
        #   )
        # ) +
        #   scale_fill_viridis_c() +
        #   ggtitle(names) +
        #   guides(fill = guide_colorbar(title = "No. DEG Up"))
      }
    )
  }
)

patchwork::wrap_plots(
  patchwork::wrap_plots(deg_venn_anno$GL0028, nrow = 1, guides = "collect"),
  patchwork::wrap_plots(deg_venn_anno$GL0038, nrow = 1, guides = "collect"),
  patchwork::wrap_plots(deg_venn_anno$GL0095, nrow = 1, guides = "collect"),
  ncol = 1
)

enrich_deg_list_anno <- imap(
  .x = deg_list_anno,
  .f = function(x, i) {
    # per sample
    imap(
      .x = x,
      .f = function(y, j) {
        # per anno
        y$couturier_cell_label |>
          unique() |>
          set_names() |>
          map(
            .f = function(z) {
              filt <- y |>
                filter(couturier_cell_label == z) |>
                filter(lfc_mean > 0) |>
                filter(is_de_fdr_0.05 == TRUE) |>
                left_join(
                  rowData(sce_scvi_list[[i]]) |>
                    as_tibble()
                )
              library(enrichR)
              enrichR::enrichr(
                genes = filt$gene_name |> as.character(),
                databases = "GO_Molecular_Function_2018"
              )
            }
          )
      }
    )
  }
)
enrich_deg_list_anno$GL0095$de_pdn_t$Progenitor |>
  as_tibble() |>
  View()
enrich_deg_list_anno$GL0095$de_pdo_t$Progenitor |>
  as_tibble() |>
  View()
volcano_plots_anno$GL0028
ggh4x::force_panelsizes(rows = unit(7.5, "cm"), cols = unit(7.5, "cm"))
volcano_plots_anno$GL0038$de_pdo_t$Astro +
  ggh4x::force_panelsizes(rows = unit(7.5, "cm"), cols = unit(7.5, "cm"))
```

```{r}
deg_list_overall <- read_csv(
  file = here("data", "processed", "4_1_tumour_broad", "per_anno_overall.csv"),
  show_col_types = FALSE
) |>
  rename(gene_id = 1)
deg_list_overall <- deg_list_overall |>
  left_join(
    y = rowData(sce_tumour) |>
      as_tibble() |>
      select(gene_id, gene_name)
  )

overall_scvi <- deg_list_overall$compar |>
    unique() |> 
  set_names() |> 
imap(
  .f = function(x, i) {
    deg_list_overall$labels |> 
      unique() |> 
      set_names() |> 
    imap(
      .f = function(y, j) {
        dat <- deg_list_overall |>
          filter(compar == x) |>
          filter(labels == y)

        # big boilerplate energy
        up_lfc <- dat |>
          filter(lfc_mean > 2) |>
          pull(gene_name)
        down_lfc <- dat |>
          filter(lfc_mean < -2) |>
          pull(gene_name)
        up_sig_label <- dat |>
          mutate(
            rank = bayes_factor * lfc_mean
          ) |>
          arrange(-rank) |>
          filter(is_de_fdr_0.05 == TRUE) |>
          filter(lfc_mean > 2) |>
          slice_head(n = 5) |>
          pull(gene_name)
        down_sig_label <- dat |>
          mutate(
            rank = bayes_factor * lfc_mean
          ) |>
          arrange(rank) |>
          filter(is_de_fdr_0.05 == TRUE) |>
          filter(lfc_mean < -2) |>
          slice_head(n = 5) |>
          pull(gene_name)

        dat <- dat |>
          mutate(
            sig = case_when(
              gene_name %in% up_lfc & is_de_fdr_0.05 == TRUE ~ "up_sig",
              gene_name %in% down_lfc & is_de_fdr_0.05 == TRUE ~ "down_sig"
            )
          ) |>
          mutate(
            colour_point = case_when(
              sig == "up_sig" ~ "#BC3D41",
              sig == "down_sig" ~ "#4F7EBB",
              .default = "grey"
            )
          ) |>
          mutate(
            label_point = case_when(
              gene_name %in% c(up_sig_label, down_sig_label) ~ gene_name,
              .default = NA_character_
            )
          )

        if (x == "pdn_t" | x == "pdn_pdo") {
          title_up <- "<span style='color:#BC3D41;'> Up in PDN &rarr;</span>"
        } else if (x == "pdo_t") {
          title_up <- "<span style='color:#BC3D41;'> Up in PDO &rarr;</span>"
        }

        if (x == "pdn_t" | x == "pdo_t") {
          title_down <- "<span style='color:#4F7EBB;;'> &larr; Up in TIS </span>"
        } else if (x == "pdn_pdo") {
          title_down <- "<span style='color:#4F7EBB;;'> &larr; Up in PDO </span>"
        }


        # x_lim <- max(abs(dat$lfc_mean))

        library(ggtext)

        # plot
        dat |>
          ggplot(
            aes(
              x = lfc_mean,
              y = bayes_factor,
              colour = colour_point,
              label = label_point,
              shape = is_de_fdr_0.05
            )
          ) +
          geom_point(show.legend = FALSE) +
          # scale_x_continuous(limits = c(-x_lim, x_lim)) +
          scale_colour_identity() +
          labs(
            y = "Bayes Factor",
            x = expression("log"[2] * "FC")
          ) +
          theme(
            aspect.ratio = 1,
            panel.background = element_rect(fill = NA, colour = "black"),
            panel.grid = element_line(colour = "grey90"),
            plot.title = element_text(size = 11),
            plot.subtitle = element_text(size = 11)
          ) +
          geom_hline(
            yintercept = dat |> filter(is_de_fdr_0.05 == FALSE) |> dplyr::slice(1) |> pull(bayes_factor),
            linetype = "dashed"
          ) +
          geom_vline(
            xintercept = c(-2, 2),
            linetype = "dashed"
          ) +
          labs(
            title = j,
            subtitle = ""
          ) +
          coord_fixed(clip = "off") +
          annotate(
            label = title_up,
            geom = "richtext",
            colour = "white",
            # label.padding = unit(c(0, 0, 0, 0), "lines"),
            x = Inf,
            y = Inf,
            vjust = -0.1,
            hjust = 1
          ) +
          annotate(
            label = title_down,
            geom = "richtext",
            colour = "white",
            # label.padding = unit(c(0, 0, 0, 0), "lines"),
            x = -Inf,
            y = Inf,
            vjust = -0.1,
            hjust = 0
          ) +
          ggrepel::geom_label_repel(
            max.overlaps = 25,
            force = 2,
            size = 10 / .pt,
            fontface = "italic"
          ) + 
          ggtitle(
            y
          )
        # patchwork::plot_annotation(
        #   title = title,
        #   theme = theme(plot.title = ggtext::element_markdown(hjust = 0.25))
        # )
      }
    )
  }
)
patchwork::wrap_plots(
patchwork::wrap_plots(overall_scvi$pdn_t, nrow = 1),
patchwork::wrap_plots(overall_scvi$pdn_t, nrow = 1),
ncol = 1
)
```

```{r}
sce_combined <- read_rds(
  file = here("data", "processed", "1_2_filtered", "sce_combined.rds")
)
sce_all <- purrr::reduce(sce_combined, cbind)



colData(sce_all) <- sce_all |> 
  colData() |> 
  as_tibble() |> 
  left_join(
    y = sce_tumour |> 
      colData() |> 
      as_tibble() |> 
      select(bc_wells, pred_single_labels, pred_cluster_labels)
  ) |> 
  DataFrame()
write_rds(
  x = sce_all,
  file = here("data", "processed", "4_2_labelled", "sce_all_labels.rds")
)
```
