---
title: "snp"
author: "zm"
date: "2024-09-02"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
set.seed(42)
```

```{r here}
library(here)
```

```{r libraries}
library(tidyverse)

conflicted::conflict_prefer_all(winner = "dplyr", quiet = TRUE)
```

```{r params}
source(file = here("eval", "scripts", "r", "params_new.r"))
data <- vector(mode = "list")
plots <- vector(mode = "list")
```

```{r import_data}
data$sample_uids <- list(
  GL0028 = list(
    "TIS" = "207686170123_R01C02",
    "PDO" = "207686170123_R12C01",
    "PDN" = "208115890066_R10C02"
  ),
  GL0038 = list(
    "TIS" = "207686170123_R02C01",
    "PDO" = "207686170123_R11C01",
    "PDN" = "208146560163_R11C02"
  ),
  GL0095 = list(
    "TIS" = "208115890028_R02C01",
    "PDO" = "208115890066_R04C01",
    "PDN" = "208115890028_R11C01"
  ),
  GL0128 = list(
    "TIS" = "208579500154_R03C01",
    "PDO" = "208115890066_R06C01",
    "PDN" = "208115890066_R12C02"
  )
)
source(here("eval/scripts/r/list_dir_n_depth.r"))
data$segment_paths <- list_dir_n_depth(
  path_use = "/stornext/Bioinf/data/lab_brain_cancer/data_processed/SNP/plots/",
  depth_keep = 2
) |>
  list.files(
    pattern = "segments",
    full.names = TRUE
  )

data$segment_paths_filt <-
  str_detect(
    data$segment_paths,
    pattern = unlist(data$sample_uids) |>
      paste(collapse = "|")
  ) %>%
  data$segment_paths[.]

data$segment_files <- map(
  .x = data$segment_paths_filt,
  .f = read_csv,
  show_col_type = FALSE
)

names(data$segment_files) <- imap(
  .x = data$sample_uids,
  .f = function(x, i) {
    paste(i, names(x), sep = "_")
  }
) |>
  unlist(use.names = FALSE)

data$segment_files <- imap(
  .x = data$segment_files,
  .f = function(x, i) {
    x |>
      mutate(sample = i) |>
      mutate(
        line = str_split(sample, pattern = "_") |> map(1) |> unlist(),
        type = str_split(sample, pattern = "_") |> map(2) |> unlist()
      )
  }
)
```

```{r plot_overall}
data$cnas_per_chr <- bind_rows(
  data$segment_files
)

data$cnas_per_chr <- data$cnas_per_chr |>
  group_by(sample, chr) |>
  mutate(diff = lead(startpos) - endpos) |>
  ungroup()

data$cnas_per_chr_index_diff <- data$cnas_per_chr_data$diff > 1e5
data$cnas_per_chr_index_diff <- which(x = data$cnas_per_chr_index_diff)

data$cnas_per_chr <- map(
  .x = data$cnas_per_chr_index_diff,
  .f = function(x) {
    data$cnas_per_chr[x, ] |>
      mutate(
        startpos = endpos + 1,
        endpos = dat[x + 1, ]$startpos - 1
      )
  }
) |>
  bind_rows(data$cnas_per_chr)

plots$cnas_per_chr <- map(
  .x = data$cnas_per_chr$line |> unique() |> sort(),
  .f = function(x) {
    ramp_loss_func <- scales::colour_ramp(c("blue", "white"))
    ramp_gain_func <- scales::colour_ramp(c("white", "red"))
    # add 1 to include white
    ramp_loss <- ramp_loss_func(x = seq(0, 1, length = 3)) |>
      head(-1)
    ramp_gain <- ramp_gain_func(x = seq(0, 1, length = 9)) |>
      tail(-1)

    data$cnas_per_chr |>
      filter(line == x) |>
      mutate(total = nMajor + nMinor) |>
      mutate(
        total = case_when(
          total > 10 ~ "> 10",
          .default = as.character(total)
        ),
      ) |>
      ggplot(
        mapping = aes(
          xmin = startpos,
          xmax = endpos,
          ymin = 0,
          ymax = 1,
          fill = total
        )
      ) +
      geom_rect(show.legend = TRUE) +
      scale_fill_manual(
        values = c(ramp_loss, "#ffffff", ramp_gain) |>
          set_names(nm = c(0:9) |> as.character(), "> 10"),
        breaks = c(c(0:9) |> as.character(), "> 10"),
        drop = FALSE
      ) +
      scale_x_continuous(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0)) +
      facet_grid(
        rows = vars(sample),
        cols = vars(chr),
        scales = "free",
        switch = "y"
      ) +
      theme(
        aspect.ratio = 1,
        panel.spacing.x = unit(0, "lines"),
        panel.spacing.y = unit(0, "lines"),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_text(angle = 0),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.25),
        strip.text.y.left = element_text(angle = 0)
      )
  }
) |>
  set_names(data$cnas_per_chr$line |> unique() |> sort())

plots$cnas_per_chr_overall <- {
  patchwork::wrap_plots(
    plots$cnas_per_chr$GL0028 +
      theme(
        legend.position = "none",
        strip.background = element_rect(fill = NA),
        strip.text.y = element_text(colour = "white"),
        strip.background.y = element_rect(fill = params$line_colours[1])
      ) +
      ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")),
    plots$cnas_per_chr$GL0038 +
      theme(
        legend.position = "none",
        strip.text.x.top = element_blank(),
        strip.background = element_rect(fill = NA),
        strip.text.y = element_text(colour = "white"),
        strip.background.y = element_rect(fill = params$line_colours[2])
      ) +
      ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")),
    plots$cnas_per_chr$GL0095 +
      theme(
        strip.text.x.top = element_blank(),
        strip.background = element_rect(fill = NA),
        strip.text.y = element_text(colour = "white"),
        strip.background.y = element_rect(fill = params$line_colours[3])
      ) +
      guides(fill = guide_legend(title = "Abs. CN")) +
      ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")),
    plots$cnas_per_chr$GL0128 +
      theme(
        legend.position = "none",
        strip.text.x.top = element_blank(),
        strip.background = element_rect(fill = NA),
        strip.text.y = element_text(colour = "white"),
        strip.background.y = element_rect(fill = params$line_colours[4])
      ) +
      ggh4x::force_panelsizes(rows = unit(0.5, "cm"), cols = unit(0.5, "cm")) +
      theme(legend.key.height = unit(0.5, "cm"), legend.key.width = unit(0.5, "cm")),
    ncol = 1,
    guides = "collect"
  )
}
```

```{r similarities}
data$manifest <- read_csv(
  file = here("meta/GSA-24v3-0_A2.csv"),
  skip = 7,
  show_col_types = FALSE
)

data$snp_positions <- data$manifest |>
  select(Chr, MapInfo) |>
  rename(chr = Chr, pos = MapInfo) |>
  arrange(chr, pos)

data$expanded_cn <- map(
  .x = data$segment_files,
  .f = function(x) {
    x <- x |>
      mutate(cn = nMajor + nMinor) |>
      pivot_longer(
        cols = c(startpos, endpos),
        values_to = "pos"
      )

    x |>
      mutate(chr = as.character(chr)) |>
      right_join(
        data$snp_positions |>
          filter(chr %in% x$chr),
        by = join_by(chr, pos),
        # this is because there are multiple snps on same pos?
        multiple = "first"
      ) |>
      arrange(chr, pos) |>
      fill(cn, sample) |>
      select(sample, chr, pos, cn)
  }
)

data$cn_similarities <- map(
  .progress = TRUE,
  .x = list(1:3, 4:6, 7:9, 10:12),
  .f = function(gl_index) {
    data_filtered <- data$expanded_cn[gl_index]
    # PDN = 1, PDO = 2, TIS = 3
    map(
      .x = list(1:2, 2:3, c(1, 3)),
      .f = function(sample_index) {
        x <- data_filtered[[sample_index[1]]] |>
          mutate(cat = paste(chr, pos, sep = "_")) |>
          rename(cn.x = cn) |>
          select(cat, cn.x) |>
          distinct(cat, .keep_all = TRUE)

        y <- data_filtered[[sample_index[2]]] |>
          mutate(cat = paste(chr, pos, sep = "_")) |>
          rename(cn.y = cn) |>
          select(cat, cn.y) |>
          distinct(cat, .keep_all = TRUE)

        stopifnot(all(x$cat == y$cat))

        tibble(
          cor = cor(x$cn.x, y$cn.y)
        )
      }
    ) |>
      set_names(c("PDN_PDO", "PDO_TIS", "PDN_TIS"))
  }
) |>
  set_names(params$sample_groups |> unique())

data$cn_similarities_plot <- imap(
  .x = data$cn_similarities,
  .f = function(x, i) {
    enframe(x) |>
      mutate(value = unlist(value)) |>
      mutate(line = i)
  }
)

library(ggpattern)

plots$correlation_line <- map(
  .x = data$cn_similarities_plot,
  .f = function(x) {
    x |>
      mutate(
        name_plot = case_when(
          name == "PDN_PDO" ~ "PDN & PDO",
          name == "PDN_TIS" ~ "PDN & TIS",
          name == "PDO_TIS" ~ "PDO & TIS",
        )
      ) |>
      ggplot(
        mapping = aes(
          # x = line,
          y = value,
          x = name_plot,
          fill = name_plot,
          pattern_fill = name_plot
        )
      ) +
      geom_col_pattern(pattern_density = 0.5, pattern_spacing = 0.2, pattern_colour = NA) +
      # geom_bar(stat = "identity") +
      scale_fill_manual(values = c(params$type_colours[c("PDN", "PDN", "PDO")] |> unname())) +
      scale_pattern_fill_manual(values = c(params$type_colours[c("PDO", "TIS", "TIS")] |> unname())) +
      labs(x = "Line", y = "Correlation") +
      theme(
        panel.background = element_rect(fill = NA, colour = "black", linewidth = 0.5),
        panel.grid = element_blank(),
        legend.key = element_rect(fill = NA, colour = "black", linewidth = 0.25),
        plot.title = element_text(size = 10),
        plot.subtitle = element_text(size = 10),
        text = element_text(size = 10),
        axis.text.x = element_text(hjust = 0, vjust = 0),
        aspect.ratio = 1
      ) +
      scale_x_discrete(
        position = "top",
        expand = c(0, 0),
        guide = guide_axis(angle = 45),
        limits = c("PDN & TIS", "PDO & TIS", "PDN & PDO")
      ) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1), position = "right")
    # facet_wrap(~line, ncol = 1) +
    # ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm"))
  }
)
plots <- snp$plots
patchwork::wrap_plots(
  plots$cnas_per_chr$GL0028 +
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      axis.ticks.x = element_blank(),
      strip.text.x = element_text(size = 8),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[1]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  plots$correlation_line$GL0028 +
    scale_y_continuous(
      limits = c(0, 1), 
      breaks = c(0, 0.5, 1), 
      labels = c("0%", "50%", "100%"),
      expand = c(0, 0), 
      position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[1]),
      # axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$cnas_per_chr$GL0038 +
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      strip.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[2]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  plots$correlation_line$GL0038 +
    scale_y_continuous(
      limits = c(0, 1), 
      breaks = c(0, 0.5, 1), 
      labels = c("0%", "50%", "100%"),
      expand = c(0, 0), 
      position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
       axis.ticks.x.top = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[2]),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$cnas_per_chr$GL0095 +
    guides(fill = guide_legend(title = "Abs. CN")) +
    theme(
      legend.position = "right",
      legend.box.margin = unit(0, "pt"),
      strip.background = element_rect(fill = NA),
      legend.title = element_text(size = 10),
      legend.key.size = unit(0.4, "cm"),
      strip.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[3]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  plots$correlation_line$GL0095 +
    scale_y_continuous(
      limits = c(0, 1), 
      breaks = c(0, 0.5, 1), 
      labels = c("0%", "50%", "100%"),
      expand = c(0, 0), 
      position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
       axis.ticks.x.top = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[3]),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$cnas_per_chr$GL0128 +
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      strip.text.x = element_blank(),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[4]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  plots$correlation_line$GL0128 +
    scale_y_continuous(
      limits = c(0, 1), 
      breaks = c(0, 0.5, 1), 
      labels = c("0%", "50%", "100%"),
      expand = c(0, 0), 
      position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
       axis.ticks.x.top = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      axis.text.x = element_blank(),
      strip.background.x = element_rect(fill = params$line_colours[4]),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  ncol = 2,
  axis_titles = "collect",
  axes = "collect",
  guides = "collect"
) 
  # patchwork::plot_annotation(title = "C")

ggsave(
  filename = here("output/snp/plots/overview.pdf"),
  device = cairo_pdf,
  width = 16,
  height = 10,
  units = "cm"
)
EnvironmentModules::module_load("texlive")
system2(
  command = "pdfcrop",
  args = c(
    here("output/snp/plots/overview.pdf"),
    here("output/snp/plots/overview.pdf")
  ),
  stdout = NULL
)
```

```{r}
patchwork::wrap_plots(
  plots$correlation_line$GL0028 +
     scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), labels = c("0%", "50", "100%"), expand = c(0, 0), position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[1]),
      # axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ylab("") + 
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$correlation_line$GL0038 +
     scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), labels = c("0%", "50", "100%"), expand = c(0, 0), position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[2]),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.ticks.x.top = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ylab("") + 
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$correlation_line$GL0095 +
     scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), labels = c("0%", "50%", "100%"), expand = c(0, 0), position = "right") + 
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[3]),
      axis.text.x = element_blank(),
       axis.ticks.x.top = element_blank(),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ylab("") + 
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$correlation_line$GL0128 +
     scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), labels = c("0%", "50", "100%"), expand = c(0, 0), position = "right") + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      axis.text.x = element_blank(),
       axis.ticks.x.top = element_blank(),
      strip.background.x = element_rect(fill = params$line_colours[4]),
      axis.title.x = element_blank(),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ylab("") + 
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  ncol = 1,
  axis_titles = "collect"
  # guides = "collect"
)

patchwork::wrap_plots(
plots$correlation_line$GL0038 +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), labels = c("0", "50", "100"), expand = c(0, 0), position = "right") + 
  # theme(axis.text.y = element_text(vjust = 1, hjust = 1)) + 
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[2]),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.ticks.x.top = element_blank()
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    # ylab("Correlation") ,
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
plots$correlation_line$GL0038 +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), labels = c("0%", "50", "100%"), expand = c(0, 0), position = "right") + 
  # theme(axis.text.y = element_text(vjust = 1, hjust = 1)) +
    theme(
      legend.position = "none",
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = NA),
      strip.text.x = element_text(size = 9, colour = "white"),
      strip.background.x = element_rect(fill = params$line_colours[2]),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.ticks.x.top = element_blank()
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) + 
    # ylab("Correlation"),
    ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
ncol = 1
) + patchwork::plot_layout(guides = "collect", axes = "collect") + 
  patchwork::plot_annotation(title = "C")
```

```{r}
patchwork::wrap_plots(
  plots$cnas_per_chr$GL0028 +
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      axis.ticks.x = element_blank(),
      strip.text.x = element_text(size = 8),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[1]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  # plots$correlation_line$GL0028 +
  #   scale_y_continuous(
  #     limits = c(0, 1), 
  #     breaks = c(0, 0.5, 1), 
  #     labels = c("0%", "50%", "100%"),
  #     expand = c(0, 0), 
  #     position = "right") + 
  #   theme(
  #     legend.position = "none",
  #     strip.background = element_rect(fill = NA),
  #     strip.text.x = element_text(size = 9, colour = "white"),
  #     strip.background.x = element_rect(fill = params$line_colours[1]),
  #     # axis.text.x = element_blank(),
  #     axis.title.x = element_blank(),
  #     # plot.margin = margin(0, 0, 0, 0, "pt")
  #   ) +
  #   ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$cnas_per_chr$GL0038 +
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      strip.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[2]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  # plots$correlation_line$GL0038 +
  #   scale_y_continuous(
  #     limits = c(0, 1), 
  #     breaks = c(0, 0.5, 1), 
  #     labels = c("0%", "50%", "100%"),
  #     expand = c(0, 0), 
  #     position = "right") + 
  #   theme(
  #     legend.position = "none",
  #      axis.ticks.x.top = element_blank(),
  #     strip.background = element_rect(fill = NA),
  #     strip.text.x = element_text(size = 9, colour = "white"),
  #     strip.background.x = element_rect(fill = params$line_colours[2]),
  #     axis.text.x = element_blank(),
  #     axis.title.x = element_blank(),
  #     # plot.margin = margin(0, 0, 0, 0, "pt")
  #   ) +
  #   ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$cnas_per_chr$GL0095 +
    guides(fill = guide_legend(title = "Abs. CN")) +
    theme(
      legend.position = "right",
      strip.background = element_rect(fill = NA),
      legend.title = element_text(size = 10),
      legend.key.size = unit(0.4, "cm"),
      strip.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[3]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  # plots$correlation_line$GL0095 +
  #   scale_y_continuous(
  #     limits = c(0, 1), 
  #     breaks = c(0, 0.5, 1), 
  #     labels = c("0%", "50%", "100%"),
  #     expand = c(0, 0), 
  #     position = "right") + 
  #   theme(
  #     legend.position = "none",
  #      axis.ticks.x.top = element_blank(),
  #     strip.background = element_rect(fill = NA),
  #     strip.text.x = element_text(size = 9, colour = "white"),
  #     strip.background.x = element_rect(fill = params$line_colours[3]),
  #     axis.text.x = element_blank(),
  #     axis.title.x = element_blank(),
  #     # plot.margin = margin(0, 0, 0, 0, "pt")
  #   ) +
  #   ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  plots$cnas_per_chr$GL0128 +
    theme(
      legend.position = "none",
      strip.background = element_rect(fill = NA),
      strip.text.x = element_blank(),
      strip.text.y = element_text(colour = "white", hjust = 0),
      strip.background.y = element_rect(fill = params$line_colours[4]),
      # plot.margin = margin(0, 0, 0, 0, "pt")
    ) +
    ggh4x::force_panelsizes(rows = unit(0.4, "cm"), cols = unit(0.4, "cm")),
  # plots$correlation_line$GL0128 +
  #   scale_y_continuous(
  #     limits = c(0, 1), 
  #     breaks = c(0, 0.5, 1), 
  #     labels = c("0%", "50%", "100%"),
  #     expand = c(0, 0), 
  #     position = "right") + 
  #   theme(
  #     legend.position = "none",
  #      axis.ticks.x.top = element_blank(),
  #     strip.background = element_rect(fill = NA),
  #     strip.text.x = element_text(size = 9, colour = "white"),
  #     axis.text.x = element_blank(),
  #     strip.background.x = element_rect(fill = params$line_colours[4]),
  #     axis.title.x = element_blank(),
  #     # plot.margin = margin(0, 0, 0, 0, "pt")
  #   ) +
  #   ggh4x::force_panelsizes(rows = unit(1.2, "cm"), cols = unit(1.2, "cm")),
  ncol = 1,
  axis_titles = "collect",
  axes = "collect",
  guides = "collect"
)
```

```{r}
# tp53_probes <- data$manifest |>
#   filter(Chr == 17) |>
#   filter(
#     between(MapInfo, left = 7675053, right = 7675236) |
#       between(MapInfo, left = 7673601, right = 7673837)
#   ) |>
#   pull(Name)
#
# data$snp_dirs <- list.dirs(
#   path = here("/stornext/Bioinf/data/lab_brain_cancer/data_raw/SNP/"),
#   recursive = FALSE
# )
#
# # extract sample sheet per chip
# data$sample_sheet <- map(
#   .x = data$snp_dirs,
#   .f = function(dir) {
#     read_delim(
#       file = list.files(
#         path = dir,
#         pattern = "Sample_Map.txt",
#         full.names = TRUE,
#         recursive = TRUE
#       ),
#       show_col_types = FALSE
#     ) |>
#       rename_with(.fn = snakecase::to_snake_case) |>
#       select(id, sentrix_position) |>
#       # this is what we use going forward
#       rename(uid = sentrix_position) |>
#       mutate(array_id = basename(dir)) |>
#       mutate(report_number = 1:n())
#   }
# ) |>
#   set_names(basename(data$snp_dirs))
#
# data$sample_sheet_collated <- bind_rows(data$sample_sheet) |>
#   mutate(
#     sample_name = str_split(
#       string = id,
#       pattern = "_"
#     ) |>
#       map_chr(1)
#   ) |>
#   mutate(sample_name = factor(sample_name))
#
# data$raw_snp_report <- map(
#   .x = data$sample_uids,
#   .f = function(x) {
#     map(
#       .x = x,
#       .f = function(y) {
#         filtered <- data$sample_sheet_collated |>
#           filter(uid %in% y)
#         path <- paste0(
#           "/stornext/Bioinf/data/lab_brain_cancer/data_raw/SNP/",
#           filtered$array_id
#         )
#         path_data <- list.files(
#           path = path,
#           pattern = paste0("FinalReport", filtered$report_number),
#           recursive = TRUE,
#           full.names = TRUE
#         )
#         read_delim(
#           file = path_data,
#           delim = "\t",
#           skip = 10,
#           show_col_types = FALSE
#         ) |>
#           rename_with(.fn = snakecase::to_snake_case)
#       }
#     )
#   }
# )
#
# imap(
#   .x = data$raw_snp_report,
#   .f = function(x, i) {
#     a <- x$TIS |>
#       filter(snp_name %in% tp53_probes) |>
#       mutate(sample_id = paste0(i, "_tissue"))
#     b <- x$PDO |>
#       filter(snp_name %in% tp53_probes) |>
#        mutate(sample_id = paste0(i, "_pdo"))
#     c <- x$PDN |>
#       filter(snp_name %in% tp53_probes) |>
#        mutate(sample_id = paste0(i, "_pdn"))
#
#     index_a <- which(a$allele_1_ab == "-" | a$allele_2_ab == "-")
#     index_b <- which(b$allele_1_ab == "-" | b$allele_2_ab == "-")
#     index_c <- which(c$allele_1_ab == "-" | c$allele_2_ab == "-")
#
#     index_final <- reduce(.x = list(index_a, index_b, index_c), .f = union)
#
#     a <- a[-index_final, ]
#     b <- b[-index_final, ]
#     c <- c[-index_final, ]
#
#     list(
#       tissue_pdo_a = all(a$allele_1_ab == b$allele_1_ab),
#       tissue_pdo_b = all(a$allele_2_ab == b$allele_2_ab),
#       tissue_pdn_a = all(a$allele_1_ab == c$allele_1_ab),
#       tissue_pdo_b = all(a$allele_2_ab == c$allele_2_ab)
#     )
#
#     bind_rows(a, b, c)
#   }
# )
#
# y <- .Last.value$GL0028
#
# x <- bind_rows(.Last.value)
#
# bind_cols(
# x |>
#   select(snp_name, sample_id, allele_1_ab, allele_2_ab, b_allele_freq),
# y |>
#   select(snp_name, sample_id, allele_1_ab, allele_2_ab, b_allele_freq) |>
#   rename_with(.fn = \(x) paste0(x, "_mut")) |>
#   rename(snp_name = 1) |>
#   filter(snp_name %in% x$snp_name)
# )
# a <- .Last.value
#
# a$allele_1_ab == a$allele_1_ab_mut
# a$allele_2_ab == a$allele_2_ab_mut
# x |>
#   group_by(snp_name) |>
#   mutate(a = case_when(allele_1_ab == allele_2_ab ~ TRUE))
```

```{r save}
write_rds(
  x = list(data = data, plots = plots),
  file = here("output/snp/plots/1_snp.rds")
)
```
