---
title: "couturier_new"
author: "zm"
date: "2024-09-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r here}
library(here)
```

```{r libraries}
require(Seurat)
require(tidyverse)
```

```{r sparse}
sparse_mat <- R.matlab::readMat(
  here("data/filtered/scRNA_GBM/gbm_sparse.mat")
)

count_matrix_sparse <- sparse_mat$RAW.COUNTS
count_matrix_sparse <- t(count_matrix_sparse)

ensembl_id <- sparse_mat$GENES |>
  as_tibble() |>
  select(V1) |>
  unlist() |>
  # unique() |>
  unname()
barcodes <- sparse_mat$barcodes |> unlist()

rownames(count_matrix_sparse) <- ensembl_id
colnames(count_matrix_sparse) <- barcodes

anno_sparse <- sparse_mat$cic |>
  as_tibble_col(column_name = "num")
anno_sparse <- anno_sparse |>
  mutate(barcode = barcodes) |>
  left_join(
    y = sparse_mat$clusters |>
      as_tibble() |>
      unlist() |>
      enframe() |>
      mutate(num = row_number()) |>
      select(num, value) |>
      rename(anno = value),
    by = "num"
  ) |> 
  mutate(sample = sparse_mat$sample |> as.character())

seurat_sparse <- CreateSeuratObject(
  counts = count_matrix_sparse[, !duplicated(colnames(count_matrix_sparse))],
  assay = "rna",
  meta.data = anno_sparse |> select(-1) |> filter(!duplicated(barcodes)),
  min.features = 1,
  project = "roadmap"
)
filt_barcodes <- anno_sparse |> 
  filter(!duplicated(barcode)) |> 
  filter(anno %in% c("astro", "tRG", "IN", "OPC", "GPC")) |> 
  pull(barcode)

seurat_sparse <- seurat_sparse[, colnames(seurat_sparse) %in% filt_barcodes]

seurat_sparse[["rna"]] <- split(seurat_sparse[["rna"]], f = seurat_sparse$sample)

rownames(seurat_sparse) <- sparse_mat$GENES |> 
  as_tibble() |> 
  select(V2) |> 
  unlist() |> 
  # unique() |> 
  unname()

cancer_mat <- R.matlab::readMat(
  here("data/filtered/annotated_cancer_data.mat")
)
hvgs <- cancer_mat[["cgenes"]] |>
  unlist() |>
  as_vector()
hvgs_name <- hvgs[552:1102] |> as.character()
hvgs_id <- hvgs[1:551] |> as.character()

seurat_sparse <- NormalizeData(seurat_sparse)
# seurat_sparse <- CellCycleScoring(
#   seurat_sparse, 
#   s.features = cc.genes$s.genes, 
#   g2m.features = cc.genes$g2m.genes, 
#   set.ident = TRUE
#   )
# seurat_sparse$Phase |> table()

seurat_sparse <- ScaleData(
  seurat_sparse, 
  # vars.to.regress = c("S.Score", "G2M.Score"), 
  features = hvgs_name,
  split.by = seurat_sparse$sample
  )
seurat_sparse <- RunPCA(seurat_sparse, npcs = 10, features = hvgs_name)
seurat_sparse <- FindNeighbors(seurat_sparse, dims = 1:10)
seurat_sparse <- FindClusters(seurat_sparse, resolution = 1)
seurat_sparse <- RunUMAP(seurat_sparse, dims = 1:10)

PCAPlot(seurat_sparse, group.by = c("seurat_clusters", "sample", "anno"))
UMAPPlot(seurat_sparse, group.by = c("seurat_clusters", "sample", "anno"))
```
