---
title: "couturier_test"
author: "zm"
date: "2024-09-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
set.seed(42)
```

```{r here}
library(here)
```

```{r libraries}
library(BiocParallel)
library(SingleCellExperiment)
library(tidyverse)

conflicted::conflict_prefer_all(winner = "dplyr", quiet = TRUE)
```

# ```{r params}
# source(file = here("eval", "scripts", "r", "params.r"))
# plots <- list()
# ```

```{r fetal}
library(Seurat)

fetal_raw <- map(
  .progress = TRUE,
  .x = list.dirs(path = here("data/filtered")) |>
    str_subset(pattern = "HFA567|HFA570|HFA571|NSC"),
  .f = function(x) {
    data <- Seurat::Read10X(
      data.dir = x,
      gene.column = 1
    )
    meta <- tibble(
      cell = colnames(data),
      sample = basename(x) |> str_extract("[^.]+"),
    ) |>
      mutate(
        line = str_extract(sample, "[^_]+"),
        sort = str_extract(sample, "[^_]+$")
      )

    SeuratObject::CreateSeuratObject(
      counts = data,
      assay = "rna",
      meta.data = meta,
      project = paste(meta$line, meta$sort, sep = "_") |>
        unique()
    )
  }
)

names(fetal_raw) <- map(
  .x = fetal_raw,
  .f = function(x) {
    paste(x$line, x$sort, sep = "_") |>
      unique()
  }
)

genes <- read_tsv(
  file = 
  "/vast/scratch/users/moore.z/pdo_compar/data/filtered/HFA567_cd133.filtered_gene_matrices/genes.tsv",
  col_names = c("gene_id", "gene_name", "gex"),
  show_col_types = FALSE
)

fetal <- map(fetal_raw, NormalizeData)
fetal <- map(fetal, FindVariableFeatures)
fetal <- map(fetal, ScaleData)

intersect_ids <- map(
  .x = fetal,
  .f = function(x) {
    rownames(x@assays$rna$scale.data)
    }
) |> 
  purrr::reduce(.f = intersect)

fetal_filt <- map(
  .x = fetal_raw,
  .f = function(x) {
    x[intersect_ids,]
  }
)
fetal_filt <- map(
  .x = 1:length(fetal_filt),
  .f = function(x) {
    RenameCells(fetal_filt[[x]], add.cell.id = x)
  }
)
names(fetal_filt) <- map(
  .x = fetal_filt,
  .f = function(x) {
    paste(x$line, x$sort, sep = "_") |>
      unique()
  }
)

fetal_filt <- purrr::reduce(fetal_filt, merge)

fetal_filt <- NormalizeData(fetal_filt)
fetal_filt <- FindVariableFeatures(fetal_filt)
fetal_filt <- ScaleData(fetal_filt)
fetal_filt <- RunPCA(fetal_filt)
fetal_filt <- FindNeighbors(fetal_filt, dims = 1:10)
fetal_filt <- FindClusters(fetal_filt)
fetal_filt <- RunUMAP(fetal_filt, dims = 1:10)
fetal_filt <- RunTSNE(fetal_filt, dims = 1:10)

PCAPlot(fetal_filt, group.by = c("seurat_clusters", "sample"))
UMAPPlot(fetal_filt, group.by = c("seurat_clusters", "sample"))
TSNEPlot(fetal_filt, group.by = c("seurat_clusters", "sample"))

FeaturePlot(fetal_filt, features = "ENSG00000131095")




sparse_mat <- R.matlab::readMat(
  here("data/filtered/scRNA_GBM/gbm_sparse.mat")
)

count_matrix <- sparse_mat$RAW.COUNTS
count_matrix <- t(count_matrix)

ensembl_id <- sparse_mat$GENES |> 
  as_tibble() |> 
  select(V1) |> 
  unlist() |> 
  # unique() |> 
  unname()
barcodes <- sparse_mat$barcodes |> unlist()

rownames(count_matrix) <- ensembl_id
colnames(count_matrix) <- barcodes

anno <- sparse_mat$cic |> 
  as_tibble_col(column_name = "num")
anno <- anno |> 
  mutate(barcode = barcodes) |> 
  left_join(
    y = sparse_mat$clusters |> 
      as_tibble() |> 
      unlist() |> 
      enframe() |> 
      mutate(num = row_number()) |> 
      select(num, value) |> 
      rename(anno = value),
    by = "num"
  )

hvgs <- Seurat::FindVariableFeatures(object = count_matrix)

hvgs_vec <- hvgs |> 
  as_tibble(rownames = "gene_id") |> 
  filter(variable == TRUE) |> 
  pull(gene_id)

count_filt <- count_matrix[rownames(count_matrix) %in% hvgs_vec, ]

# umap_res <- uwot::umap(X = t(count_filt))
# 
# umap_res |> 
#   as_tibble(rownames = "barcode") |> 
#   left_join(
#     y = anno,
#     by = "barcode",
#     relationship = "many-to-many"
#     ) |> 
#   ggplot(
#     mapping = aes(
#       x = V1,
#       y = V2,
#       colour = anno
#     )
#   ) + 
#   geom_point()


library(Seurat)

seurat_obj <- SeuratObject::CreateSeuratObject(
      counts = count_matrix[, !duplicated(colnames(count_matrix))],
      assay = "rna",
      meta.data = anno |> select(-1) |> filter(!duplicated(barcodes)),
      min.features = 1,
      project = "roadmap"
    )

seurat_obj <- Seurat::NormalizeData(seurat_obj)

cancer_mat <- R.matlab::readMat(
  here("data/filtered/annotated_cancer_data.mat")
)
hvgs <- cancer_mat[["cgenes"]] |> unlist() |> as_vector()
hvgs_name <- hvgs[552:1102] |> as.character()
hvgs_id <- hvgs[1:551] |> as.character()

rownames(seurat_obj) <- sparse_mat$GENES |> 
  as_tibble() |> 
  select(V2) |> 
  unlist() |> 
  # unique() |> 
  unname()

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
seurat_obj <- CellCycleScoring(
  seurat_obj, 
  s.features = s.genes, 
  g2m.features = g2m.genes, 
  set.ident = TRUE
  )
seurat_obj$S.Score |> hist()
seurat_obj$G2M.Score |> hist()
seurat_obj$Phase |> table()

seurat_obj <- Seurat::ScaleData(
  seurat_obj, 
  # vars.to.regress = c("S.Score", "G2M.Score"), 
  features = hvgs_name
  )
seurat_obj <- Seurat::RunPCA(seurat_obj, npcs = 10, features = hvgs_name)
seurat_obj <- Seurat::FindNeighbors(seurat_obj, dims = 1:10)
seurat_obj <- Seurat::FindClusters(seurat_obj, resolution = 1)
seurat_obj <- Seurat::RunUMAP(seurat_obj, dims = 1:10)
# seurat_obj <- Seurat::RunTSNE(seurat_obj, dims = 1:10)
Seurat::DimPlot(seurat_obj, group.by = c("seurat_clusters", "anno"))
# Seurat::DimPlot(seurat_obj, group.by = c("seurat_clusters", "anno"), reduction = "tsne")

filt_barcodes <- anno |> 
  filter(!duplicated(barcode)) |> 
  filter(anno %in% c("astro", "tRG", "IN", "OPC", "GPC")) |> 
  pull(barcode)

seurat_obj_filt <- seurat_obj[, colnames(seurat_obj) %in% filt_barcodes]
# seurat_obj_filt_filt <- seurat_obj_filt[, !seurat_obj_filt$Phase %in% c("G2M", "S")]

Seurat::DimPlot(seurat_obj_filt, group.by = c("seurat_clusters", "anno"))

seurat_obj_filt$new_anno <- case_when(
  seurat_obj_filt$seurat_clusters == 1 & seurat_obj_filt$anno == "IN" ~ "in",
  seurat_obj_filt$seurat_clusters == 17 & seurat_obj_filt$anno == "OPC" ~ "opc",
  seurat_obj_filt$seurat_clusters == 11 & seurat_obj_filt$anno == "GPC" ~ "gpc",
  seurat_obj_filt$seurat_clusters == 11 & seurat_obj_filt$anno == "astro" ~ "astro",
  seurat_obj_filt$seurat_clusters == 14 & seurat_obj_filt$anno == "tRG" ~ "trg"
)

seurat_obj_filt <- seurat_obj_filt[, !is.na(seurat_obj_filt$new_anno)]

seurat_obj_filt <- Seurat::NormalizeData(seurat_obj_filt)

seurat_obj_filt <- Seurat::ScaleData(
  seurat_obj_filt, 
  # vars.to.regress = c("S.Score", "G2M.Score"),
  features = hvgs_name |> as.character(),
  # features = FindVariableFeatures(seurat_obj_filt),
  # do.center = TRUE,
  scale.max = 2
  )
seurat_obj_filt <- Seurat::RunPCA(
  seurat_obj_filt, 
  npcs = 50, 
  features = hvgs_name |> as.character(),
  weight.by.var = TRUE
  )

# seurat_obj_filt <- Seurat::RunPCA(
#   seurat_obj_filt, 
#   npcs = 10, 
#   features = rownames(seurat_obj_filt)
  # )
DimPlot(seurat_obj_filt, group.by = "anno", reduction = "pca")
# DimPlot(seurat_obj_filt, group.by = "anno", reduction = "pca", dims = c(2, 3))
seurat_obj_filt <- Seurat::FindNeighbors(seurat_obj_filt)
seurat_obj_filt <- Seurat::FindClusters(seurat_obj_filt, resolution = 1, group.singletons = FALSE)
seurat_obj_filt <- Seurat::RunUMAP(seurat_obj_filt, dims = 1:10)

Seurat::DimPlot(seurat_obj_filt, group.by = c("seurat_clusters", "anno", "new_anno"))

# pca_new <- prcomp(x = seurat_obj_filt@assays$rna$scale.data)

dm <- destiny::DiffusionMap(
  data = seurat_obj_filt@reductions$pca@cell.embeddings,
  # data = pca_new$rotation[, 1:10],
  # sigma = "local",
  distance = "euclidean",
  k = 50,
  n_local = 10
  # n_pcs = 10
  # n_eigs = 10
  # density_norm = FALSE
  )

plot(dm)

tib <- dm@eigenvectors |> 
  as_tibble(rownames = "barcode") |> 
  left_join(
    y = seurat_obj_filt@meta.data |> 
      as_tibble()
    )

tib |> 
  ggplot(
    mapping = aes(
      x = DC2,
      y = DC3,
      colour = anno
    )
  ) + 
  geom_point() + 
  # xlim(-0.03, -0.01) + 
  # scale_y_continuous(transform = "log10") +
  theme(aspect.ratio = 1)

qplot(y = destiny::eigenvalues(dm)) 

library(plotly)
plot_ly(
  data = tib,
  x = ~DC1,
  y = ~DC2,
  z = ~DC3,
  color = ~tib$anno,
  colors = c('#e86e41','#d9b53f','#9857ba','#57ba64','#57b7ba'),
  marker = list(size = 1, width=1),
  type = "scatter3d",
  mode = "markers"
)

dm_pred <- destiny::dm_predict(
  dm = dm,
  new_data = seurat_obj_filt@reductions$pca@cell.embeddings[1:200, ]
)

plot(dm,    2:3,     col     = palette()[[6]],
     new_dcs = dm_pred, col_new = palette()[[4]])

lda_model <- MASS::lda(anno ~ ., data = tib |> select(c(2:21, 25)) |> slice(200:n()))

pred <- predict(lda_model, tib |> select(c(2:21, 25)) |> slice(1:200), method = "predictive")

pred$class
pred$actual <- tib$anno[1:200]

tibble(
  pred$class,
  pred$actual
)
which(pred$class != pred$actual)

pred$posterior[which(pred$class != pred$actual), ]

tib$wrong_pred <- "right"

tib$wrong_pred[which(pred$class != pred$actual)] <- "wrong"

tib |> 
  ggplot(
    mapping = aes(
      x = DC2,
      y = DC3,
      colour = anno,
      shape = wrong_pred
    )
  ) + 
  geom_point() + 
  geom_point(aes(colour = wrong_pred))
  # xlim(-0.03, -0.01) + 
  # scale_y_continuous(transform = "log10") +
  theme(aspect.ratio = 1)

which(pred$class != pred$actual)

source("/vast/scratch/users/moore.z/pdo_compar/eval/scripts/r/load_ref_list.r")
ref_list <- load_ref_list()
ref_list$couturier$Sample |> table()
sample_filt <- ref_list$couturier[, ref_list$couturier$Sample == "filtered/BT400.filtered_gene_matrices/"]

seurat_sample_filt <- CreateSeuratObject(
  counts = counts(sample_filt),
  meta.data = colData(sample_filt) |> as.data.frame(),
  assay = "rna"
)

seurat_sample_filt <- Seurat::NormalizeData(seurat_sample_filt)



seurat_sample_filt <- Seurat::ScaleData(
  seurat_sample_filt, 
  # vars.to.regress = c("S.Score", "G2M.Score"),
  features = hvgs_id |> as.character(),
  # features = FindVariableFeatures(seurat_obj_filt),
  # do.center = TRUE,
  scale.max = 2
  )
seurat_sample_filt <- Seurat::RunPCA(
  seurat_sample_filt, 
  # npcs = 10, 
  features = hvgs_id |> as.character(),
  weight.by.var = TRUE
  )

# seurat_obj_filt <- Seurat::RunPCA(
#   seurat_obj_filt, 
#   npcs = 10, 
#   features = rownames(seurat_obj_filt)
  # )
DimPlot(seurat_sample_filt, group.by = "cluster", reduction = "pca")
# DimPlot(seurat_obj_filt, group.by = "anno", reduction = "pca", dims = c(2, 3))
seurat_sample_filt <- Seurat::FindNeighbors(seurat_sample_filt)
seurat_sample_filt <- Seurat::FindClusters(seurat_sample_filt, resolution = 1, group.singletons = FALSE)
seurat_sample_filt <- Seurat::RunUMAP(seurat_sample_filt, dims = 1:10)

Seurat::DimPlot(seurat_sample_filt, group.by = c("seurat_clusters", "cluster"))

dm_pred_sample <- destiny::dm_predict(
  dm = dm,
  new_data = seurat_sample_filt@reductions$pca@cell.embeddings
)
plot(dm,    2:3,     col     = palette()[[6]],
     new_dcs = dm_pred_sample, col_new = palette()[[4]])

pred_sample <- predict(lda_model, dm_pred_sample, method = "predictive")

post_tib <- pred_sample$posterior |> 
  as_tibble()

post_tib

sample_actual <- sample_filt$cluster
sample_pred <- pred_sample$class

table(sample_actual == sample_pred |> as.character())


seurat_sample <- CreateSeuratObject(
  counts = counts(ref_list$couturier),
  meta.data = colData(ref_list$couturier) |> as.data.frame(),
  assay = "rna"
)
seurat_sample[["rna"]] <- split(seurat_sample[["rna"]], f = seurat_sample$Sample)
seurat_sample <- Seurat::NormalizeData(seurat_sample)

cancer_mat <- R.matlab::readMat(
  here("data/filtered/annotated_cancer_data.mat")
)
hvgs <- cancer_mat[["cgenes"]] |> unlist() |> as_vector()
hvgs_name <- hvgs[552:1102] |> as.character()
hvgs_id <- hvgs[1:551] |> as.character()

seurat_sample <- Seurat::ScaleData(
  seurat_sample, 
  # vars.to.regress = c("S.Score", "G2M.Score"),
  features = hvgs_id |> as.character(),
  # features = FindVariableFeatures(seurat_obj_filt),
  # do.center = TRUE,
  split.by = seurat_sample$Sample,
  scale.max = 2
  )
seurat_sample <- Seurat::RunPCA(
  seurat_sample, 
  npcs = 10,
  features = hvgs_id |> as.character(),
  weight.by.var = TRUE
  )

# seurat_obj_filt <- Seurat::RunPCA(
#   seurat_obj_filt, 
#   npcs = 10, 
#   features = rownames(seurat_obj_filt)
  # )
DimPlot(seurat_sample, group.by = "cluster", reduction = "pca")
# DimPlot(seurat_obj_filt, group.by = "anno", reduction = "pca", dims = c(2, 3))
seurat_sample <- Seurat::FindNeighbors(seurat_sample)
seurat_sample <- Seurat::FindClusters(seurat_sample, resolution = 1, group.singletons = FALSE)
seurat_sample <- Seurat::RunUMAP(seurat_sample, dims = 1:10)

Seurat::DimPlot(seurat_sample, group.by = c("seurat_clusters", "cluster", "Sample"))

dm_sample <- destiny::DiffusionMap(
  data = seurat_sample@reductions$pca@cell.embeddings,
  # data = pca_new$rotation[, 1:10],
  # sigma = "local",
  distance = "euclidean",
  k = 50,
  n_local = 10
  # n_pcs = 10
  # n_eigs = 10
  # density_norm = FALSE
  )

plot(dm_sample)

tib <- dm_sample@eigenvectors |> 
  as_tibble() |> 
  mutate(cell = row_number()) |> 
  left_join(
    y = seurat_sample@meta.data |> 
      as_tibble()|> 
  mutate(cell = row_number())
    )

tib |> 
  ggplot(
    mapping = aes(
      x = DC1,
      y = DC2,
      colour = cluster
    )
  ) + 
  geom_point() + 
  # xlim(-0.03, -0.01) + 
  # scale_y_continuous(transform = "log10") +
  theme(aspect.ratio = 1)

library(plotly)
plot_ly(
  data = tib,
  x = ~DC2,
  y = ~DC4,
  z = ~DC3,
  color = ~tib$cluster,
  colors = c('#e86e41','#d9b53f','#9857ba','#57ba64','#57b7ba'),
  marker = list(size = 1, width=1),
  type = "scatter3d",
  mode = "markers"
)


dm_sample <- destiny::di

dm_pred_sample <- destiny::dm_predict(
  dm = dm,
  new_data = seurat_sample@reductions$pca@cell.embeddings
)
plot(dm,    2:3,     col     = palette()[[6]],
     new_dcs = dm_pred_sample, col_new = palette()[[4]])

pred_sample <- predict(lda_model, dm_sample, method = "predictive")

post_tib <- pred_sample$posterior |> 
  as_tibble()

post_tib

sample_actual <- sample_filt$cluster
sample_pred <- pred_sample$class

table(sample_actual == sample_pred |> as.character())









tibble(
  sample_actual,
  sample_pred
)


MASS::lda(Speceis ~ ., data = iris)
count_filt_filt <- count_filt[count_filt_fitibble_row()lt <- count_filt[
  rownames(count_filt) %in% hvgs_id, 
  colnames(count_filt) %in% filt_barcodes
  ]
anno_filt <- anno |> select(-1) |> 
  filter(!duplicated(barcodes)) |> 
  filter(barcode %in% filt_barcodes)
# tRG, neuron, astro, GPC, OLC

pca_res <- RunPCA(count_filt_filt, npcs = 10)

dm <- destiny::DiffusionMap(
  data = pca_res@cell.embeddings,
  k = 50
  )

plot(dm)

dm@eigenvectors |> 
  as_tibble(rownames = "barcode") |> 
  left_join(anno_filt) |> 
  ggplot(
    mapping = aes(
      x = DC1,
      y = DC2,
      colour = barcode
    )
  ) + 
  geom_point()

fetal_integrated <- IntegrateLayers(
  object = fetal,
  method = CCAIntegration,
  orig.reduction = "pca",
  new.reduction = "integrated.cca",
  verbose = TRUE
  # assay = "rna",
  # layers = "scale.data"
)

fetal_integrated <- FindNeighbors(
  fetal_integrated, 
  k.param = 50,
  reduction = "integrated.cca", 
  # dims = 1:10
  )
fetal_integrated <- FindClusters(
  fetal_integrated,
  method = "igraph",
  group.singletons = FALSE
  )
fetal_integrated <- RunUMAP(
  fetal_integrated, 
  reduction = "integrated.cca", 
  dims = 1:30,
  n.neighbors = 5,
  min.dist = 0.01,
  return.model = TRUE
  )
# fetal_integrated <- RunTSNE(fetal_integrated)

UMAPPlot(
  object = fetal_integrated,
  group.by = c("sample", "seurat_clusters"),
  label = TRUE
)

# ok so paper focuses on tRG, neuron, astro, GPC, OLC
# where are??

# olc fig 2 == apod high
patchwork::wrap_plots(
  DimPlot(
    object = fetal_integrated,
    group.by = "seurat_clusters",
    label = TRUE
  ),
  FeaturePlot(
    object = fetal_integrated,
    # apod
    features = "ENSG00000189058"
  )
)
# olc == 18

# gpc == pdgfra and not olc
patchwork::wrap_plots(
  DimPlot(
    object = fetal_integrated,
    group.by = "seurat_clusters",
    label = TRUE
  ),
  FeaturePlot(
    object = fetal_integrated,
    # pdgrfa
    features = "ENSG00000134853"
  ),
  FeaturePlot(
    object = fetal_integrated,
    # apod
    features = "ENSG00000189058"
  )
)

patchwork::wrap_plots(
  DimPlot(
    object = fetal_integrated,
    group.by = "seurat_clusters",
    label = TRUE
  ),
  FeaturePlot(
    object = fetal_integrated,
    # gfap
    features = "ENSG00000131095"
  ),
  FeaturePlot(
    object = fetal_integrated,
    # hes1 high from sup data
    features = "ENSG00000114315"
  )
)


markers <- FindAllMarkers(
  object = JoinLayers(fetal_integrated),
  min.pct = 0.25,
  only.pos = TRUE
)

fetal_integrated_filt <- fetal_integrated[, colnames(fetal_integrated) %in% anno$barcode]

fetal_integrated_filt$anno <- anno$anno

TSNEPlot(fetal_integrated_filt, group.by = "anno")
```

```{r}
library(Seurat)

fetal <- map(
  .progress = TRUE,
  .x = list.dirs(path = here("data/filtered")) |>
    str_subset(pattern = "HFA567|HFA570|HFA571|NSC"),
  .f = function(x) {
    data <- Seurat::Read10X(
      data.dir = x,
      gene.column = 1
    )
    # genes <- read_tsv(
    #   file = paste(x, "genes.tsv", sep = "/"),
    #   show_col_types = FALSE
    # )
    meta <- tibble(
      cell = colnames(data),
      sample = basename(x) |> str_extract("[^.]+"),
    ) |>
      mutate(
        line = str_extract(sample, "[^_]+"),
        sort = str_extract(sample, "[^_]+$")
      )

    SeuratObject::CreateSeuratObject(
      counts = data,
      assay = "rna",
      meta.data = meta,
      project = paste(meta$line, meta$sort, sep = "_") |>
        unique()
    )
  }
)

names(fetal) <- map(
  .x = fetal,
  .f = function(x) {
    paste(x$line, x$sort, sep = "_") |>
      unique()
  }
)

fetal <- purrr::reduce(.x = fetal, .f = merge)

fetal <- FindVariableFeatures(fetal, nfeatures = 3000)
fetal <- NormalizeData(fetal, scale.factor = 1e5)
fetal <- ScaleData(fetal, scale.max = 3)
```


```{r}
library(Seurat)

fetal_list <- map(
  .progress = TRUE,
  .x = list.dirs(path = here("data/filtered")) |>
    str_subset(pattern = "HFA567|HFA570|HFA571|NSC"),
  .f = function(x) {
    data <- Seurat::Read10X(
      data.dir = x,
      gene.column = 1
    )
    # genes <- read_tsv(
    #   file = paste(x, "genes.tsv", sep = "/"),
    #   show_col_types = FALSE
    # )
    # meta <- tibble(
    #   cell = colnames(data),
    #   sample = basename(x) |> str_extract("[^.]+"),
    # ) |>
    #   mutate(
    #     line = str_extract(sample, "[^_]+"),
    #     sort = str_extract(sample, "[^_]+$")
    #   )
    # 
    # SeuratObject::CreateSeuratObject(
    #   counts = data,
    #   assay = "rna",
    #   meta.data = meta,
    #   project = paste(meta$line, meta$sort, sep = "_") |>
    #     unique()
    # )
    data
  }
)

genes <- read_tsv(
  file = paste(list.dirs(path = here("data/filtered"))[2], "genes.tsv", sep = "/"),
  show_col_types = FALSE,
  col_names = c("ensembl_id", "gene_name")
)

mito_genes <- genes |> 
  filter(str_detect(gene_name, pattern = "MT-")) |> 
  pull(ensembl_id)

fetal_list <- map(
  .x = fetal_list,
  .f = function(x) {
    column_sum <- colSums(x[!rownames(x) %in% mito_genes, ])
    mito_sum <- colSums(x[rownames(x) %in% mito_genes, ])
    ratio <- mito_sum/column_sum
    x[, ratio < 0.12]
  }
)

hvgs <- map(
  .x = fetal_list,
  .f = function(x) {
    stat <- FindVariableFeatures(x)
    row_index <- stat$vst.variance |> 
      enframe(name = "index", value = "var") |> 
      arrange(-var) |> 
      dplyr::slice(1:3000) |> 
      pull(index)
    row_index
  }
)

fetal_list <- map2(
  .x = fetal_list,
  .y = hvgs,
  .f = function(x, y) {
    x[y, ]
  }
)

z_list <- map(
  .x = fetal_list,
  .f = function(x) {
    t(scale(t(x)))
  }
)

intersect_all <- purrr::reduce(
  .x = z_list |> map(rownames),
  .f = intersect
  )

z_merge <- map(
  .x = z_list,
  .f = function(x) {
    x[intersect_all, ]
  }
) |> 
  purrr::reduce(.f = cbind)

pca_res <- RunPCA(z_merge, npcs = 1)
umap_res <- uwot::umap(X = pca_res@feature.loadings, n_neighbors = 10, learning_rate = 5)
plot(umap_res[,1] ~ umap_res[, 2])

dm <- destiny::DiffusionMap(
  data = pca_res@feature.loadings,
  k = 50
  )
plot(dm)

ggplot(
  data = dm,
  mapping = aes(DC2, DC3)
) + 
  geom_point()
```
